import { BaseGenerator } from './lib/base-generator.mjs';

const gen = new BaseGenerator('django', 'Django');

const LEVELS = [
  { levelId: 'beginer', nameId: 'Pemula', nameEn: 'Beginner', descId: 'Dasar Django: Setup, Models, Views, Templates.', descEn: 'Django basics: Setup, Models, Views, Templates.' },
  { levelId: 'intermediate', nameId: 'Menengah', nameEn: 'Intermediate', descId: 'Forms, Auth, Admin, REST.', descEn: 'Forms, Auth, Admin, REST.' },
  { levelId: 'advanced', nameId: 'Lanjutan', nameEn: 'Advanced', descId: 'Testing, Caching, Deployment, Project.', descEn: 'Testing, Caching, Deployment, Project.' }
];

const MODULES = [
  { week: 1, level: 'beginer', topicId: 'setup-django', titleId: 'Setup & Struktur Project', titleEn: 'Setup & Project Structure', programId: 'Halo Django', programEn: 'Hello Django', levelNameId: 'Pemula', levelNameEn: 'Beginner', language: 'python',
    code: '# Setup Django\n# pip install django\n# django-admin startproject myproject\n# python manage.py startapp myapp\n\nprint("=== Django Setup ===")\nprint("1. pip install django")\nprint("2. django-admin startproject myproject")\nprint("3. python manage.py startapp myapp")\nprint("4. python manage.py runserver")\nprint("")\nprint("=== Struktur Folder ===")\nprint("myproject/")\nprint("  manage.py")\nprint("  myproject/")\nprint("    settings.py")\nprint("    urls.py")\nprint("  myapp/")\nprint("    models.py")\nprint("    views.py")\nprint("    admin.py")',
    objectivesId: ['Install Django dan setup project', 'django-admin startproject dan startapp', 'Struktur folder Django', 'Settings: INSTALLED_APPS, DATABASES', 'Run development server'],
    objectivesEn: ['Install Django and setup project', 'django-admin startproject and startapp', 'Django folder structure', 'Settings: INSTALLED_APPS, DATABASES', 'Run development server'],
    explanationId: '### Install\npip install django. pip freeze untuk lihat versi.\n\n### Start Project\ndjango-admin startproject name.\n\n### Start App\npython manage.py startapp name.\n\n### Settings\nINSTALLED_APPS, DATABASES, MIDDLEWARE di settings.py.',
    explanationEn: '### Install\npip install django.\n\n### Start Project\ndjango-admin startproject.\n\n### Start App\npython manage.py startapp.\n\n### Settings\nConfiguration in settings.py.',
    experimentsId: ['Buat project dan app pertama', 'Coba runserver', 'Tambah app ke INSTALLED_APPS', 'Setup database PostgreSQL'],
    experimentsEn: ['Create first project and app', 'Run server', 'Add app to INSTALLED_APPS', 'Setup PostgreSQL'],
    challengeId: 'Setup project: buat app, konfigurasi settings, run server.',
    challengeEn: 'Setup project: create app, configure settings, run server.',
    summaryId: 'Minggu 1 dari 12: **Setup Django** (Level: Pemula).',
    summaryEn: 'Week 1 of 12: **Django Setup** (Level: Beginner).' },

  { week: 2, level: 'beginer', topicId: 'models-orm', titleId: 'Models & ORM', titleEn: 'Models & ORM', programId: 'Model Produk', programEn: 'Product Model', levelNameId: 'Pemula', levelNameEn: 'Beginner', language: 'python',
    code: '# Models & ORM\nprint("=== Django Model ===")\nprint("class Produk(models.Model):")\nprint("    nama = models.CharField(max_length=200)")\nprint("    harga = models.DecimalField(max_digits=10, decimal_places=2)")\nprint("    deskripsi = models.TextField(blank=True)")\nprint("    stok = models.IntegerField(default=0)")\nprint("    tersedia = models.BooleanField(default=True)")\nprint("    created = models.DateTimeField(auto_now_add=True)")\nprint("")\nprint("=== Field Types ===")\nprint("CharField, TextField, IntegerField, DecimalField")\nprint("BooleanField, DateTimeField, ForeignKey, ManyToMany")\nprint("")\nprint("=== Migration ===")\nprint("python manage.py makemigrations")\nprint("python manage.py migrate")',
    objectivesId: ['Model: class turunan models.Model', 'Field types: CharField, IntegerField, DecimalField', 'Relationships: ForeignKey, ManyToManyField', 'Migrations: makemigrations, migrate', 'QuerySet API: filter, exclude, get'],
    objectivesEn: ['Model: class extending models.Model', 'Field types: CharField, IntegerField, DecimalField', 'Relationships: ForeignKey, ManyToManyField', 'Migrations: makemigrations, migrate', 'QuerySet API: filter, exclude, get'],
    explanationId: '### Model\nClass turunan models.Model. Setiap class = tabel.\n\n### Fields\nCharField (string), IntegerField (angka), DecimalField (uang).\n\n### Migration\nmakemigrations -> migrate.\n\n### QuerySet\nModel.objects.filter(), .all(), .get().',
    explanationEn: '### Model\nClass extending models.Model.\n\n### Fields\nField types.\n\n### Migration\nSchema versioning.\n\n### QuerySet\nQuery API.',
    experimentsId: ['Buat model Product', 'Buat relationship: Category -> Product', 'Jalankan migration', 'Coba QuerySet di shell'],
    experimentsEn: ['Create Product model', 'Create relationship', 'Run migration', 'Try QuerySet'],
    challengeId: 'Buat models: Category, Product, Review dengan relationships.',
    challengeEn: 'Create models: Category, Product, Review with relationships.',
    summaryId: 'Minggu 2 dari 12: **Models & ORM** (Level: Pemula).',
    summaryEn: 'Week 2 of 12: **Models & ORM** (Level: Beginner).' },

  { week: 3, level: 'beginer', topicId: 'views-urls', titleId: 'Views & URLconf', titleEn: 'Views & URLconf', programId: 'View Produk', programEn: 'Product View', levelNameId: 'Pemula', levelNameEn: 'Beginner', language: 'python',
    code: "# Views & URLconf\nprint('=== Function-Based Views ===')\nprint('def product_list(request):')\nprint('    products = Product.objects.all()')\nprint('    return render(request, products/list.html, {products: products})')\nprint('')\nprint('=== URL Configuration ===')\nprint('from django.urls import path')\nprint('urlpatterns = [')\nprint('    path(products/, views.product_list, name=product-list),')\nprint('    path(products/<int:pk>/, views.product_detail, name=product-detail),')\nprint(']')",
    objectivesId: ['Function-Based Views (FBV)', 'URL patterns dengan path()', 'URL parameters: <int:pk>', 'Template rendering dengan render()', 'Class-Based Views (CBV)'],
    objectivesEn: ['Function-Based Views (FBV)', 'URL patterns with path()', 'URL parameters', 'Template rendering', 'Class-Based Views (CBV)'],
    explanationId: '### FBV\ndef view(request): return render.\n\n### URLconf\nurlpatterns = [path(url, view)].\n\n### Parameters\n<int:pk> capture integer.\n\n### CBV\nclass MyView(View): def get(self, request):',
    explanationEn: '### FBV\nFunction views.\n\n### URLconf\nURL patterns.\n\n### Parameters\nURL capture groups.\n\n### CBV\nClass-based views.',
    experimentsId: ['Buat views CRUD products', 'Setup URLs dengan parameters', 'Coba Class-Based View', '404 handling'],
    experimentsEn: ['Create CRUD views', 'Setup URL parameters', 'Try CBV', '404 handling'],
    challengeId: 'Buat views: list, detail, create, update, delete.',
    challengeEn: 'Create views: list, detail, create, update, delete.',
    summaryId: 'Minggu 3 dari 12: **Views & URLconf** (Level: Pemula).',
    summaryEn: 'Week 3 of 12: **Views & URLconf** (Level: Beginner).' },

  { week: 4, level: 'beginer', topicId: 'templates', titleId: 'Templates & Static Files', titleEn: 'Templates & Static Files', programId: 'Template Produk', programEn: 'Product Template', levelNameId: 'Pemula', levelNameEn: 'Beginner', language: 'python',
    code: '# Templates\nprint("=== Template Syntax ===")\nprint("{{ variable }} - Output variable")\nprint("{% tag %} - Template tag")\nprint("{% for item in items %} - Loop")\nprint("{% endfor %}")\nprint("")\nprint("=== Template Inheritance ===")\nprint("base.html: <h1>{% block content %}{% endblock %}</h1>")\nprint("child.html: {% extends 'base.html' %}")\nprint("  {% block content %}Page Content{% endblock %}")\nprint("")\nprint("=== Static Files ===")\nprint("{% load static %}")\nprint("{% static 'css/style.css' %}")',
    objectivesId: ['Template syntax: {{ }}, {% %}', 'Template inheritance: extends, block', 'Built-in tags: for, if, include', 'Static files: {% static %}', 'Template filters: date, truncatewords'],
    objectivesEn: ['Template syntax: {{ }}, {% %}', 'Template inheritance: extends, block', 'Built-in tags: for, if, include', 'Static files: {% static %}', 'Template filters'],
    explanationId: '### Syntax\n{{ variable }} untuk output. {% tag %} untuk logic.\n\n### Inheritance\n{% extends %}, {% block %}, {% include %}.\n\n### Static\n{% load static %}, {% static path %}.',
    explanationEn: '### Syntax\nTemplate syntax.\n\n### Inheritance\nTemplate inheritance.\n\n### Static\nStatic file handling.',
    experimentsId: ['Buat base.html dan child templates', 'Loop dan conditional', 'Setup static files', 'Custom template filter'],
    experimentsEn: ['Create templates', 'Loops and conditionals', 'Static files', 'Custom filter'],
    challengeId: 'Buat template structure: base, list, detail, form.',
    challengeEn: 'Create template structure: base, list, detail, form.',
    summaryId: 'Minggu 4 dari 12: **Templates** (Level: Pemula).',
    summaryEn: 'Week 4 of 12: **Templates** (Level: Beginner).' },

  { week: 5, level: 'intermediate', topicId: 'forms', titleId: 'Forms & Validation', titleEn: 'Forms & Validation', programId: 'Form Produk', programEn: 'Product Form', levelNameId: 'Menengah', levelNameEn: 'Intermediate', language: 'python',
    code: '# Forms & Validation\nprint("=== Django Form ===")\nprint("class ProductForm(forms.Form):")\nprint("    nama = forms.CharField(max_length=200)")\nprint("    harga = forms.DecimalField(max_digits=10, decimal_places=2)")\nprint("    stok = forms.IntegerField(min_value=0)")\nprint("")\nprint("=== ModelForm ===")\nprint("class ProductModelForm(forms.ModelForm):")\nprint("    class Meta:")\nprint("        model = Product")\nprint("        fields = ['nama', 'harga', 'stok']")\nprint("")\nprint("=== Validation ===")\nprint("form.is_valid() -> True/False")\nprint("form.cleaned_data -> validated data")',
    objectivesId: ['forms.Form untuk custom form', 'forms.ModelForm untuk model-based form', 'Validation: is_valid(), cleaned_data', 'Custom validation: clean_<field>', 'Widgets dan labels'],
    objectivesEn: ['forms.Form for custom forms', 'forms.ModelForm for model-based forms', 'Validation: is_valid(), cleaned_data', 'Custom validation: clean_<field>', 'Widgets and labels'],
    explanationId: '### Form\nforms.Form atau forms.ModelForm.\n\n### Validation\nform.is_valid() -> True/False.\n\n### ModelForm\nAuto-generate dari model.\n\n### Custom Validation\ndef clean_field(self):',
    explanationEn: '### Form\nForm classes.\n\n### Validation\nis_valid() and cleaned_data.\n\n### ModelForm\nModel-based forms.\n\n### Custom Validation\nField-level validation.',
    experimentsId: ['Buat Form dan ModelForm', 'Custom validation', 'Form widgets styling', 'File upload'],
    experimentsEn: ['Create Form and ModelForm', 'Custom validation', 'Widgets styling', 'File upload'],
    challengeId: 'Buat form: ProductForm dengan validation.',
    challengeEn: 'Create form: ProductForm with validation.',
    summaryId: 'Minggu 5 dari 12: **Forms** (Level: Menengah).',
    summaryEn: 'Week 5 of 12: **Forms** (Level: Intermediate).' },

  { week: 6, level: 'intermediate', topicId: 'auth', titleId: 'Authentication & Authorization', titleEn: 'Authentication & Authorization', programId: 'Auth System', programEn: 'Auth System', levelNameId: 'Menengah', levelNameEn: 'Intermediate', language: 'python',
    code: '# Authentication\nprint("=== Auth System ===")\nprint("from django.contrib.auth.models import User")\nprint("from django.contrib.auth import authenticate, login, logout")\nprint("from django.contrib.auth.decorators import login_required")\nprint("")\nprint("=== Login ===")\nprint("user = authenticate(request, username=..., password=...)")\nprint("if user: login(request, user)")\nprint("")\nprint("=== Register ===")\nprint("User.objects.create_user(username, email, password)")\nprint("")\nprint("=== Login Required ===")\nprint("@login_required")\nprint("def profile(request): pass")',
    objectivesId: ['User model dan auth system', 'Login, logout, register views', '@login_required decorator', 'Permissions dan groups', 'Custom user model'],
    objectivesEn: ['User model and auth system', 'Login, logout, register views', '@login_required decorator', 'Permissions and groups', 'Custom user model'],
    explanationId: '### Auth\nDjango built-in auth: login, logout, authenticate.\n\n### Login Required\n@login_required decorator untuk protect views.\n\n### Permissions\n@permission_required untuk check permission.',
    explanationEn: '### Auth\nBuilt-in auth system.\n\n### Login Required\nProtect views.\n\n### Permissions\nPermission checks.',
    experimentsId: ['Buat login/logout views', 'Register view', 'Profile view dengan @login_required', 'Custom permissions'],
    experimentsEn: ['Create login/logout views', 'Register view', 'Profile view', 'Custom permissions'],
    challengeId: 'Buat auth system: login, register, profile, logout.',
    challengeEn: 'Build auth system: login, register, profile, logout.',
    summaryId: 'Minggu 6 dari 12: **Auth** (Level: Menengah).',
    summaryEn: 'Week 6 of 12: **Auth** (Level: Intermediate).' },

  { week: 7, level: 'intermediate', topicId: 'admin', titleId: 'Admin Interface', titleEn: 'Admin Interface', programId: 'Admin Customization', programEn: 'Admin Customization', levelNameId: 'Menengah', levelNameEn: 'Intermediate', language: 'python',
    code: '# Admin Interface\nprint("=== Register Model ===")\nprint("from django.contrib import admin")\nprint("@admin.register(Product)")\nprint("class ProductAdmin(admin.ModelAdmin):")\nprint("    list_display = ('nama', 'harga', 'stok')")\nprint("    list_filter = ('tersedia', 'category')")\nprint("    search_fields = ('nama', 'deskripsi')")\nprint("")\nprint("=== Custom Actions ===")\nprint("actions = ['make_available']")\nprint("def make_available(self, request, queryset):")\nprint("    queryset.update(tersedia=True)")',
    objectivesId: ['@admin.register decorator', 'list_display, list_filter, search_fields', 'Custom actions', 'Inlines: TabularInline, StackedInline', 'Custom admin templates'],
    objectivesEn: ['@admin.register decorator', 'list_display, list_filter, search_fields', 'Custom actions', 'Inlines', 'Custom admin templates'],
    explanationId: '### Register\n@admin.register(Model) atau admin.site.register().\n\n### Configuration\nlist_display, list_filter, search_fields.\n\n### Actions\nCustom bulk actions untuk queryset.',
    explanationEn: '### Register\nRegister models.\n\n### Configuration\nAdmin display options.\n\n### Actions\nBulk actions.',
    experimentsId: ['Customize ProductAdmin', 'Buat custom action', 'Tambah inline untuk Review', 'Custom admin template'],
    experimentsEn: ['Customize ProductAdmin', 'Create custom action', 'Add inline', 'Custom template'],
    challengeId: 'Customize admin: list display, filters, search, actions.',
    challengeEn: 'Customize admin: list display, filters, search, actions.',
    summaryId: 'Minggu 7 dari 12: **Admin** (Level: Menengah).',
    summaryEn: 'Week 7 of 12: **Admin** (Level: Intermediate).' },

  { week: 8, level: 'intermediate', topicId: 'rest-api', titleId: 'Django REST Framework', titleEn: 'Django REST Framework', programId: 'REST API', programEn: 'REST API', levelNameId: 'Menengah', levelNameEn: 'Intermediate', language: 'python',
    code: '# Django REST Framework\n# pip install djangorestframework\n\nprint("=== Serializer ===")\nprint("from rest_framework import serializers")\nprint("class ProductSerializer(serializers.ModelSerializer):")\nprint("    class Meta:")\nprint("        model = Product")\nprint("        fields = ['id', 'nama', 'harga', 'stok']")\nprint("")\nprint("=== ViewSet ===")\nprint("from rest_framework import viewsets")\nprint("class ProductViewSet(viewsets.ModelViewSet):")\nprint("    queryset = Product.objects.all()")\nprint("    serializer_class = ProductSerializer")\nprint("")\nprint("=== Router ===")\nprint("from rest_framework.routers import DefaultRouter")\nprint("router = DefaultRouter()")\nprint("router.register('products', ProductViewSet)")',
    objectivesId: ['Serializer: ModelSerializer', 'ViewSet: ModelViewSet', 'Router: DefaultRouter', 'Permissions: IsAuthenticated', 'Filtering dan pagination'],
    objectivesEn: ['Serializer: ModelSerializer', 'ViewSet: ModelViewSet', 'Router: DefaultRouter', 'Permissions: IsAuthenticated', 'Filtering and pagination'],
    explanationId: '### Serializer\nConvert model instance <-> JSON.\n\n### ViewSet\nCRUD otomatis: list, create, retrieve, update, destroy.\n\n### Router\nAuto-generate URL patterns.',
    explanationEn: '### Serializer\nModel <-> JSON conversion.\n\n### ViewSet\nAutomatic CRUD.\n\n### Router\nURL generation.',
    experimentsId: ['Buat API untuk Product', 'Tambah authentication', 'Custom permissions', 'Pagination'],
    experimentsEn: ['Create Product API', 'Add authentication', 'Custom permissions', 'Pagination'],
    challengeId: 'Buat REST API: Product, Category dengan auth.',
    challengeEn: 'Build REST API: Product, Category with auth.',
    summaryId: 'Minggu 8 dari 12: **DRF** (Level: Menengah).',
    summaryEn: 'Week 8 of 12: **DRF** (Level: Intermediate).' },

  { week: 9, level: 'advanced', topicId: 'testing', titleId: 'Testing Django', titleEn: 'Testing Django', programId: 'Test Suite', programEn: 'Test Suite', levelNameId: 'Lanjutan', levelNameEn: 'Advanced', language: 'python',
    code: '# Testing Django\nprint("=== TestCase ===")\nprint("from django.test import TestCase")\nprint("class ProductTest(TestCase):")\nprint("    def setUp(self):")\nprint("        Product.objects.create(nama='Test', harga=100)")\nprint("")\nprint("    def test_create(self):")\nprint("        p = Product.objects.get(nama='Test')")\nprint("        self.assertEqual(p.harga, 100)")\nprint("")\nprint("=== APITestCase ===")\nprint("from rest_framework.test import APITestCase")\nprint("class ProductAPITest(APITestCase):")\nprint("    def test_list(self):")\nprint("        response = self.client.get('/api/products/')")\nprint("        self.assertEqual(response.status_code, 200)")',
    objectivesId: ['TestCase untuk unit test', 'APITestCase untuk API test', 'Client untuk simulate requests', 'Fixtures dan factories', 'Coverage: pytest-cov'],
    objectivesEn: ['TestCase for unit tests', 'APITestCase for API tests', 'Client for simulating requests', 'Fixtures and factories', 'Coverage: pytest-cov'],
    explanationId: '### TestCase\nclass TestX(TestCase): def test_method(self).\n\n### APITestCase\nTest REST API endpoints.\n\n### Client\nself.client.get(), self.client.post().',
    explanationEn: '### TestCase\nTest case classes.\n\n### APITestCase\nAPI testing.\n\n### Client\nSimulate HTTP requests.',
    experimentsId: ['Test models dan views', 'Test API endpoints', 'Test authentication', 'Factories dengan factory_boy'],
    experimentsEn: ['Test models and views', 'Test API endpoints', 'Test auth', 'Factories with factory_boy'],
    challengeId: 'Buat test suite: models, views, API, 80%+ coverage.',
    challengeEn: 'Build test suite: models, views, API, 80%+ coverage.',
    summaryId: 'Minggu 9 dari 12: **Testing** (Level: Lanjutan).',
    summaryEn: 'Week 9 of 12: **Testing** (Level: Advanced).' },

  { week: 10, level: 'advanced', topicId: 'caching', titleId: 'Caching & Performance', titleEn: 'Caching & Performance', programId: 'Cache Strategy', programEn: 'Cache Strategy', levelNameId: 'Lanjutan', levelNameEn: 'Advanced', language: 'python',
    code: '# Caching & Performance\nprint("=== Cache Framework ===")\nprint("from django.core.cache import cache")\nprint("cache.set('key', 'value', timeout=3600)")\nprint("cache.get('key')")\nprint("")\nprint("=== Per-View Cache ===")\nprint("from django.views.decorators.cache import cache_page")\nprint("@cache_page(60 * 15)")\nprint("def product_list(request): pass")\nprint("")\nprint("=== Query Optimization ===")\nprint("Product.objects.select_related('category')")\nprint("Product.objects.prefetch_related('reviews')")',
    objectivesId: ['Cache framework: cache.set, cache.get', '@cache_page decorator', 'select_related dan prefetch_related', 'N+1 query problem', 'Database indexing'],
    objectivesEn: ['Cache framework: cache.set, cache.get', '@cache_page decorator', 'select_related and prefetch_related', 'N+1 query problem', 'Database indexing'],
    explanationId: '### Cache\ncache.set(key, value, timeout). cache.get(key).\n\n### Per-View Cache\n@cache_page(seconds) untuk cache halaman.\n\n### Optimization\nselect_related (JOIN), prefetch_related (separate query).',
    explanationEn: '### Cache\nCache API.\n\n### Per-View Cache\nView-level caching.\n\n### Optimization\nQuery optimization.',
    experimentsId: ['Setup Redis cache', 'Cache fragment template', 'Optimize queries dengan select_related', 'Database indexing'],
    experimentsEn: ['Setup Redis cache', 'Cache template fragments', 'Optimize queries', 'Database indexing'],
    challengeId: 'Optimasi: caching, query optimization, indexing.',
    challengeEn: 'Optimize: caching, query optimization, indexing.',
    summaryId: 'Minggu 10 dari 12: **Caching** (Level: Lanjutan).',
    summaryEn: 'Week 10 of 12: **Caching** (Level: Advanced).' },

  { week: 11, level: 'advanced', topicId: 'deployment', titleId: 'Deployment & DevOps', titleEn: 'Deployment & DevOps', programId: 'Production Setup', programEn: 'Production Setup', levelNameId: 'Lanjutan', levelNameEn: 'Advanced', language: 'python',
    code: '# Deployment & DevOps\nprint("=== Production Settings ===")\nprint("DEBUG = False")\nprint("ALLOWED_HOSTS = ['example.com']")\nprint("SECRET_KEY = os.environ['SECRET_KEY']")\nprint("")\nprint("=== Gunicorn ===")\nprint("pip install gunicorn")\nprint("gunicorn myproject.wsgi:application")\nprint("")\nprint("=== Nginx Config ===")\nprint("location / { proxy_pass http://127.0.0.1:8000; }")\nprint("location /static/ { alias /path/to/static/; }")\nprint("")\nprint("=== Docker ===")\nprint("FROM python:3.11-slim")\nprint("COPY requirements.txt .")\nprint("RUN pip install -r requirements.txt")\nprint("CMD gunicorn myproject.wsgi --bind 0.0.0.0:8000")',
    objectivesId: ['Production settings: DEBUG=False, ALLOWED_HOSTS', 'Gunicorn WSGI server', 'Nginx reverse proxy', 'Docker containerization', 'Environment variables'],
    objectivesEn: ['Production settings', 'Gunicorn WSGI server', 'Nginx reverse proxy', 'Docker containerization', 'Environment variables'],
    explanationId: '### Settings\nDEBUG=False, SECRET_KEY dari env, ALLOWED_HOSTS.\n\n### Gunicorn\nWSGI server untuk production.\n\n### Nginx\nReverse proxy + static files.\n\n### Docker\nContainerize Django app.',
    explanationEn: '### Settings\nProduction configuration.\n\n### Gunicorn\nProduction WSGI server.\n\n### Nginx\nReverse proxy.\n\n### Docker\nContainerization.',
    experimentsId: ['Setup Gunicorn', 'Nginx config', 'Dockerfile + docker-compose', 'CI/CD pipeline'],
    experimentsEn: ['Setup Gunicorn', 'Nginx config', 'Dockerfile + docker-compose', 'CI/CD pipeline'],
    challengeId: 'Deploy Django: Gunicorn, Nginx, Docker, CI/CD.',
    challengeEn: 'Deploy Django: Gunicorn, Nginx, Docker, CI/CD.',
    summaryId: 'Minggu 11 dari 12: **Deployment** (Level: Lanjutan).',
    summaryEn: 'Week 11 of 12: **Deployment** (Level: Advanced).' },

  { week: 12, level: 'advanced', topicId: 'capstone', titleId: 'Capstone: Django Application', titleEn: 'Capstone: Django Application', programId: 'E-Commerce Site', programEn: 'E-Commerce Site', levelNameId: 'Lanjutan', levelNameEn: 'Advanced', language: 'python',
    code: '# Capstone: E-Commerce Site\nprint("=== Capstone: E-Commerce ===")\nprint("Features:")\nprint("  - User auth (register, login, profile)")\nprint("  - Product catalog (CRUD, categories)")\nprint("  - Shopping cart")\nprint("  - Order management")\nprint("  - Admin interface")\nprint("  - REST API")\nprint("  - Tests")\nprint("  - Docker deployment")\nprint("")\nprint("=== Project Structure ===")\nprint("  apps/")\nprint("    accounts/")\nprint("    products/")\nprint("    orders/")\nprint("    cart/")\nprint("  templates/")\nprint("  static/")\nprint("  tests/")',
    objectivesId: ['Menggabungkan semua konsep Django', 'Professional project structure', 'Auth, CRUD, Admin, API', 'Testing: unit + integration', 'Deployment: Docker, CI/CD'],
    objectivesEn: ['Combine all Django concepts', 'Professional project structure', 'Auth, CRUD, Admin, API', 'Testing: unit + integration', 'Deployment: Docker, CI/CD'],
    explanationId: '### Structure\napps/ untuk setiap feature: accounts, products, orders, cart.\n\n### Features\nAuth, Product CRUD, Cart, Orders, Admin, API.\n\n### Testing\nTestCase, APITestCase, coverage.',
    explanationEn: '### Structure\nOrganized app structure.\n\n### Features\nComplete e-commerce features.\n\n### Testing\nComprehensive tests.',
    experimentsId: ['Payment integration', 'Email notifications', 'Search', 'Celery tasks'],
    experimentsEn: ['Payment integration', 'Email notifications', 'Search', 'Celery tasks'],
    challengeId: 'Buat E-Commerce lengkap: auth, products, cart, orders, admin, API, tests, Docker.',
    challengeEn: 'Build complete E-Commerce: auth, products, cart, orders, admin, API, tests, Docker.',
    summaryId: 'Minggu 12 dari 12: **Capstone** (Level: Lanjutan). Selesai!',
    summaryEn: 'Week 12 of 12: **Capstone** (Level: Advanced). Complete!' }
];

for (const level of LEVELS) {
  level.weeks = MODULES.filter(m => m.level === level.levelId).map(m => ({
    week: m.week, topicId: m.topicId, titleId: m.titleId, titleEn: m.titleEn,
  }));
}

gen.writeFiles(MODULES, LEVELS);
