import sys
sys.path.insert(0, 'scripts')
from _helper import create_generator_file

LEVELS = [
  {"levelId": "beginer", "nameId": "Pemula", "nameEn": "Beginner", "descId": "Dasar Node.js: runtime, modules, file system, events.", "descEn": "Node.js basics: runtime, modules, file system, events."},
  {"levelId": "intermediate", "nameId": "Menengah", "nameEn": "Intermediate", "descId": "Backend: Express, REST API, auth, database.", "descEn": "Backend: Express, REST API, auth, database."},
  {"levelId": "advanced", "nameId": "Lanjutan", "nameEn": "Advanced", "descId": "Production: testing, performance, deployment, capstone.", "descEn": "Production: testing, performance, deployment, capstone."}
]

MODULES = [
  {
    "week": 1, "level": "beginer", "topicId": "dasar-nodejs",
    "titleId": "Dasar Node.js & Runtime", "titleEn": "Node.js Basics & Runtime",
    "programId": "Halo Node.js", "programEn": "Hello Node.js",
    "levelNameId": "Pemula", "levelNameEn": "Beginner",
    "language": "javascript",
    "code": "const nama = \"Node.js\";\nconsole.log(\"Selamat datang di \" + nama + \"!\");\nconsole.log(\"Versi: \" + process.version);\nconsole.log(\"Platform: \" + process.platform);\n\nconst umur = 25;\nconst tinggi = 175.5;\nconst aktif = true;\nconst hobi = [\"ngoding\", \"baca buku\", \"musik\"];\nconst profil = { nama: \"Budi\", kota: \"Jakarta\" };\n\nconsole.log(\"Umur: \" + umur + \" tahun\");\nconsole.log(\"Hobi: \" + hobi.join(\", \"));\nconsole.log(\"Profil: \" + profil.nama + \" dari \" + profil.kota);\n\nfunction sapa(nama) { return \"Halo, \" + nama + \"!\"; }\nconst kali = (a, b) => a * b;\n\nconsole.log(sapa(\"Gopher\"));\nconsole.log(\"5 x 3 = \" + kali(5, 3));",
    "objectivesId": ["Memahami apa itu Node.js dan perannya sebagai JavaScript runtime", "Menjalankan file JavaScript dengan node command", "Mengenal process object: version, platform, argv", "Variabel: const, let, dan tipe data dasar JavaScript", "Function declaration vs arrow function"],
    "objectivesEn": ["Understand what Node.js is and its role as a JavaScript runtime", "Run JavaScript files with the node command", "Learn process object: version, platform, argv", "Variables: const, let, and basic JavaScript data types", "Function declarations vs arrow functions"],
    "explanationId": "### Apa Itu Node.js\nNode.js adalah JavaScript runtime berbasis V8 engine.\n\n### Process Object\nprocess.version, process.platform, process.argv.\n\n### Variabel\nconst tidak bisa di-reassign, let bisa, var hindari.\n\n### Function\nFunction declaration vs arrow function.",
    "explanationEn": "### What is Node.js\nNode.js is a JavaScript runtime powered by V8.\n\n### Process Object\nprocess.version, process.platform, process.argv.\n\n### Variables\nconst, let, avoid var.\n\n### Functions\nFunction declarations vs arrow functions.",
    "experimentsId": ["Ubah nilai variabel dan lihat perubahannya", "Tambah function baru dengan parameter berbeda", "Coba process.argv dengan argumen custom", "Buat arrow function dengan multiple parameters"],
    "experimentsEn": ["Change variable values and observe", "Add a new function with different parameters", "Try process.argv with custom arguments", "Create arrow function with multiple parameters"],
    "challengeId": "Buat program CLI sapaan: terima nama dari process.argv, output sapaan dengan timestamp.",
    "challengeEn": "Build a CLI greeting: accept name from process.argv, output greeting with timestamp.",
    "summaryId": "Minggu 1 dari 12: **Dasar Node.js & Runtime** (Level: Pemula). Minggu depan: **Modules & NPM**.",
    "summaryEn": "Week 1 of 12: **Node.js Basics & Runtime** (Level: Beginner). Next week: **Modules & NPM**."
  },
  {
    "week": 2, "level": "beginer", "topicId": "modules-npm",
    "titleId": "Modules & NPM", "titleEn": "Modules & NPM",
    "programId": "Sistem Modul", "programEn": "Module System",
    "levelNameId": "Pemula", "levelNameEn": "Beginner",
    "language": "javascript",
    "code": "const fs = require(\"fs\");\nconst path = require(\"path\");\nconst os = require(\"os\");\n\nconsole.log(\"=== Core Modules ===\");\nconsole.log(\"CPU:\", os.cpus().length + \" cores\");\nconsole.log(\"Free memory:\", Math.round(os.freemem() / 1024 / 1024) + \" MB\");\n\nconst math = {\n  tambah: (a, b) => a + b,\n  kurang: (a, b) => a - b,\n  kali: (a, b) => a * b,\n  bagi: (a, b) => b !== 0 ? a / b : NaN,\n  rataRata: (arr) => arr.reduce((a, b) => a + b, 0) / arr.length\n};\n\nconsole.log(\"\\n=== Local Module ===\");\nconsole.log(\"10 + 5 =\", math.tambah(10, 5));\nconsole.log(\"10 - 5 =\", math.kurang(10, 5));\nconsole.log(\"Rata-rata [10,20,30]:\", math.rataRata([10, 20, 30]));\n\nconsole.log(\"\\n=== Daftar Core Modules ===\");\nconst modules = { fs: \"File system\", path: \"Path manipulation\", os: \"System info\", http: \"HTTP server\", events: \"Event emitter\" };\nfor (const [key, val] of Object.entries(modules)) {\n  console.log(\"  - \" + key + \": \" + val);\n}",
    "objectivesId": ["Mengenal 3 jenis module: core, local, dan npm", "CommonJS: require() dan module.exports", "Core modules: fs, path, os, http, events", "NPM: init, install, package.json scripts", "ES Modules: import/export (Node.js 14+)"],
    "objectivesEn": ["Learn 3 module types: core, local, and npm", "CommonJS: require() and module.exports", "Core modules: fs, path, os, http, events", "NPM: init, install, package.json scripts", "ES Modules: import/export (Node.js 14+)"],
    "explanationId": "### CommonJS vs ES Modules\nCommonJS: require() dan module.exports. ES Modules: import dan export.\n\n### Core Modules\nfs (file system), path (path manipulation), os (system info), http (HTTP server), events (event emitter).\n\n### NPM\nnpm init, npm install <pkg>, npm run <script>.",
    "explanationEn": "### CommonJS vs ES Modules\nrequire()/module.exports vs import/export.\n\n### Core Modules\nfs, path, os, http, events.\n\n### NPM\nnpm init, npm install, npm run.",
    "experimentsId": ["Buat module sendiri dengan exports beberapa fungsi", "Coba path.join dan path.resolve", "Buat package.json dengan scripts custom", "Implementasikan ES module dengan .mjs"],
    "experimentsEn": ["Create your own module with multiple exports", "Try path.join and path.resolve", "Create package.json with custom scripts", "Implement ES module with .mjs"],
    "challengeId": "Buat module kalkulator: tambah, kurang, kali, bagi, rata-rata, median. Export sebagai object.",
    "challengeEn": "Build a calculator module: add, subtract, multiply, divide, average, median. Export as object.",
    "summaryId": "Minggu 2 dari 12: **Modules & NPM** (Level: Pemula). Minggu depan: **File System & Path**.",
    "summaryEn": "Week 2 of 12: **Modules & NPM** (Level: Beginner). Next week: **File System & Path**."
  },
  {
    "week": 3, "level": "beginer", "topicId": "file-system",
    "titleId": "File System & Path", "titleEn": "File System & Path",
    "programId": "Manajer File", "programEn": "File Manager",
    "levelNameId": "Pemula", "levelNameEn": "Beginner",
    "language": "javascript",
    "code": "const path = require(\"path\");\n\nconsole.log(\"=== Path Operations ===\");\nconsole.log(\"Filename:\", path.basename(\"data/users/budi.json\"));\nconsole.log(\"Dirname:\", path.dirname(\"data/users/budi.json\"));\nconsole.log(\"Extname:\", path.extname(\"data/users/budi.json\"));\nconsole.log(\"Joined:\", path.join(\"data\", \"users\", \"budi.json\"));\nconsole.log(\"Resolved:\", path.resolve(\"data\", \"users\"));\n\nconsole.log(\"\\n=== File List Simulation ===\");\nconst files = [\n  { name: \"data.txt\", size: 1024, type: \"text/plain\" },\n  { name: \"foto.jpg\", size: 204800, type: \"image/jpeg\" },\n  { name: \"video.mp4\", size: 10485760, type: \"video/mp4\" },\n];\nfor (const f of files) {\n  const sizeKB = (f.size / 1024).toFixed(1);\n  console.log(\"  \" + f.name + \" (\" + sizeKB + \" KB) - \" + f.type);\n}\n\nconsole.log(\"\\n=== JSON Parse ===\");\nconst jsonString = '{\"nama\":\"Budi\",\"umur\":25,\"hobi\":[\"ngoding\",\"membaca\"]}';\nconst parsed = JSON.parse(jsonString);\nconsole.log(\"Nama:\", parsed.nama, \"Hobi:\", parsed.hobi.join(\", \"));\n\nconsole.log(\"\\n=== JSON Output ===\");\nconst newData = { nama: \"Siti\", umur: 23, hobi: [\"desain\", \"memasak\"] };\nconsole.log(JSON.stringify(newData, null, 2));",
    "objectivesId": ["Path module: join, resolve, basename, dirname, extname", "fs.readFileSync dan fs.writeFileSync untuk baca/tulis file", "fs.promises untuk async file operations", "JSON.parse dan JSON.stringify untuk data serialization", "Direktori: mkdir, readdir, stat untuk info file"],
    "objectivesEn": ["Path module: join, resolve, basename, dirname, extname", "fs.readFileSync and fs.writeFileSync for file read/write", "fs.promises for async file operations", "JSON.parse and JSON.stringify for data serialization", "Directories: mkdir, readdir, stat for file info"],
    "explanationId": "### Path Module\njoin gabung path, resolve absolute path, parse decompose path.\n\n### File System\nSync: readFileSync, writeFileSync. Async: fs.promises.readFile.\n\n### JSON\nJSON.parse(string) menjadi object. JSON.stringify(object) menjadi string.",
    "explanationEn": "### Path Module\njoin, resolve, parse.\n\n### File System\nSync and async operations.\n\n### JSON\nParse and stringify.",
    "experimentsId": ["Baca file JSON dan tampilkan dalam format table", "Buat fungsi untuk cek apakah file exists", "Implementasikan copy file dari source ke destination", "Buat recursive directory listing"],
    "experimentsEn": ["Read JSON file and display in table format", "Create function to check if file exists", "Implement copy file from source to destination", "Create recursive directory listing"],
    "challengeId": "Buat program manajemen catatan: baca/tulis file JSON, tambah/hapus catatan, cari berdasarkan judul.",
    "challengeEn": "Build a note management program: read/write JSON files, add/delete notes, search by title.",
    "summaryId": "Minggu 3 dari 12: **File System & Path** (Level: Pemula). Minggu depan: **Events & EventEmitter**.",
    "summaryEn": "Week 3 of 12: **File System & Path** (Level: Beginner). Next week: **Events & EventEmitter**."
  },
  {
    "week": 4, "level": "beginer", "topicId": "events-async",
    "titleId": "Events & Async Programming", "titleEn": "Events & Async Programming",
    "programId": "Event Emitter", "programEn": "Event Emitter",
    "levelNameId": "Pemula", "levelNameEn": "Beginner",
    "language": "javascript",
    "code": "const EventEmitter = require(\"events\");\n\nclass Logger extends EventEmitter {\n  log(level, message) {\n    const timestamp = new Date().toISOString();\n    this.emit(\"log\", { timestamp, level, message });\n  }\n}\n\nconst logger = new Logger();\nlogger.on(\"log\", (data) => {\n  console.log(\"[\" + data.timestamp + \"] \" + data.level + \": \" + data.message);\n});\nlogger.log(\"INFO\", \"Aplikasi dimulai\");\nlogger.log(\"WARN\", \"Memory usage tinggi\");\nlogger.log(\"ERROR\", \"Koneksi database gagal\");\n\nconsole.log(\"\\n=== Promise Pattern ===\");\nfunction getUser(id) {\n  return new Promise((resolve, reject) => {\n    if (id > 0) resolve({ id, nama: \"User \" + id });\n    else reject(new Error(\"ID tidak valid\"));\n  });\n}\n\ngetUser(1).then(user => {\n  console.log(\"User:\", user.nama);\n  return getUser(2);\n}).then(user => {\n  console.log(\"User:\", user.nama);\n}).catch(err => {\n  console.log(\"Error:\", err.message);\n});\n\nconsole.log(\"\\n=== Async/Await ===\");\nasync function loadUsers() {\n  const u1 = await getUser(1);\n  const u2 = await getUser(2);\n  console.log(\"Loaded:\", u1.nama + \", \" + u2.nama);\n}\nloadUsers();",
    "objectivesId": ["EventEmitter: on, emit, once, removeListener", "Callback pattern: error-first callback (Node.js convention)", "Promise: then, catch, finally, Promise.all", "Async/await: syntactic sugar untuk Promise", "Event loop: setTimeout, setImmediate, process.nextTick"],
    "objectivesEn": ["EventEmitter: on, emit, once, removeListener", "Callback pattern: error-first callback (Node.js convention)", "Promise: then, catch, finally, Promise.all", "Async/await: syntactic sugar for Promises", "Event loop: setTimeout, setImmediate, process.nextTick"],
    "explanationId": "### EventEmitter\non daftarkan listener, emit trigger event, once sekali dengar.\n\n### Callback\nError-first: callback(err, result).\n\n### Promise & Async/Await\nPromise untuk async operation. async/await untuk synchronous-looking async code.",
    "explanationEn": "### EventEmitter\non, emit, once.\n\n### Callbacks\nError-first pattern.\n\n### Promises & Async/Await\nPromise chains and async/await syntax.",
    "experimentsId": ["Buat class sendiri yang extends EventEmitter", "Implementasikan Promise.all dengan 3 promise", "Coba setTimeout vs setImmediate", "Buat retry logic dengan Promise dan async/await"],
    "experimentsEn": ["Create your own class extending EventEmitter", "Implement Promise.all with 3 promises", "Try setTimeout vs setImmediate", "Create retry logic with Promises and async/await"],
    "challengeId": "Buat event-driven logger: EventEmitter dengan level (info, warn, error), write ke file, dan filter by level.",
    "challengeEn": "Build an event-driven logger: EventEmitter with levels (info, warn, error), write to file, and filter by level.",
    "summaryId": "Minggu 4 dari 12: **Events & Async Programming** (Level: Pemula). Selesai fase Beginner! Minggu depan: **Express.js & Web Server** (Intermediate).",
    "summaryEn": "Week 4 of 12: **Events & Async Programming** (Level: Beginner). Beginner phase complete! Next week: **Express.js & Web Server** (Intermediate)."
  },
  {
    "week": 5, "level": "intermediate", "topicId": "express-server",
    "titleId": "Express.js & Web Server", "titleEn": "Express.js & Web Server",
    "programId": "Web Server Dasar", "programEn": "Basic Web Server",
    "levelNameId": "Menengah", "levelNameEn": "Intermediate",
    "language": "javascript",
    "code": "const express = require(\"express\");\nconst app = express();\nconst PORT = 3000;\n\napp.use(express.json());\n\napp.get(\"/\", (req, res) => {\n  res.json({ message: \"Selamat datang di API!\" });\n});\n\napp.get(\"/users\", (req, res) => {\n  const users = [{ id: 1, nama: \"Budi\" }, { id: 2, nama: \"Siti\" }];\n  res.json(users);\n});\n\napp.get(\"/users/:id\", (req, res) => {\n  const id = parseInt(req.params.id);\n  res.json({ id, nama: \"User \" + id });\n});\n\napp.post(\"/users\", (req, res) => {\n  const { nama, email } = req.body;\n  res.status(201).json({ id: 3, nama, email });\n});\n\napp.listen(PORT, () => {\n  console.log(\"Server berjalan di http://localhost:\" + PORT);\n});",
    "objectivesId": ["Express.js: setup, routes, dan listen di port", "HTTP methods: GET, POST, PUT, DELETE", "Route parameters: req.params dan req.query", "Middleware: app.use, next(), error handler", "Request body parsing: express.json(), express.urlencoded()"],
    "objectivesEn": ["Express.js: setup, routes, and listen on port", "HTTP methods: GET, POST, PUT, DELETE", "Route parameters: req.params and req.query", "Middleware: app.use, next(), error handler", "Request body parsing: express.json(), express.urlencoded()"],
    "explanationId": "### Express Setup\nconst app = express(), app.listen(port, callback).\n\n### Routes\napp.get(), app.post(), app.put(), app.delete().\n\n### Middleware\napp.use(middleware) global, app.get(path, mw1, mw2, handler) route-specific, next() lanjut ke middleware berikutnya.",
    "explanationEn": "### Express Setup\nexpress() and app.listen().\n\n### Routes\nHTTP method handlers.\n\n### Middleware\nGlobal and route-specific middleware with next().",
    "experimentsId": ["Tambah route PUT dan DELETE untuk users", "Buat middleware custom untuk logging request", "Implementasikan route dengan query string filter", "Tambah error handling middleware"],
    "experimentsEn": ["Add PUT and DELETE routes for users", "Create custom middleware for request logging", "Implement route with query string filter", "Add error handling middleware"],
    "challengeId": "Buat REST API untuk Task Manager: CRUD tasks dengan Express, middleware logging, dan error handling.",
    "challengeEn": "Build a REST API for Task Manager: CRUD tasks with Express, logging middleware, and error handling.",
    "summaryId": "Minggu 5 dari 12: **Express.js & Web Server** (Level: Menengah). Minggu depan: **REST API Design**.",
    "summaryEn": "Week 5 of 12: **Express.js & Web Server** (Level: Intermediate). Next week: **REST API Design**."
  },
  {
    "week": 6, "level": "intermediate", "topicId": "rest-api",
    "titleId": "REST API Design", "titleEn": "REST API Design",
    "programId": "API Produk", "programEn": "Product API",
    "levelNameId": "Menengah", "levelNameEn": "Intermediate",
    "language": "javascript",
    "code": "console.log(\"=== REST API Design Principles ===\");\n\nconst resources = [\n  { resource: \"/products\", description: \"Koleksi produk\" },\n  { resource: \"/products/123\", description: \"Produk spesifik\" },\n  { resource: \"/products/123/reviews\", description: \"Review produk\" },\n];\nconsole.log(\"Resource Naming:\");\nfor (const r of resources) console.log(\"  \" + r.resource + \" -> \" + r.description);\n\nconsole.log(\"\\n=== HTTP Methods ===\");\nconst methods = [\n  { method: \"GET\", action: \"Baca resource\", idempotent: \"Ya\" },\n  { method: \"POST\", action: \"Buat baru\", idempotent: \"Tidak\" },\n  { method: \"PUT\", action: \"Update seluruh\", idempotent: \"Ya\" },\n  { method: \"DELETE\", action: \"Hapus\", idempotent: \"Ya\" },\n];\nfor (const m of methods) console.log(\"  \" + m.method + \": \" + m.action);\n\nconsole.log(\"\\n=== Status Codes ===\");\nconst codes = [\n  { code: 200, meaning: \"OK - sukses\" },\n  { code: 201, meaning: \"Created\" },\n  { code: 400, meaning: \"Bad Request\" },\n  { code: 404, meaning: \"Not Found\" },\n  { code: 500, meaning: \"Server Error\" },\n];\nfor (const c of codes) console.log(\"  \" + c.code + \": \" + c.meaning);\n\nconsole.log(\"\\n=== Response Format ===\");\nconst response = { status: \"success\", data: { id: 1, nama: \"Laptop\" }, message: \"OK\" };\nconsole.log(JSON.stringify(response, null, 2));",
    "objectivesId": ["Resource-based URLs: /resources, /resources/:id", "HTTP methods mapping: GET, POST, PUT, DELETE", "Status codes: 200, 201, 400, 404, 500", "Request/Response format: JSON structure", "Pagination, sorting, filtering untuk collection endpoints"],
    "objectivesEn": ["Resource-based URLs: /resources, /resources/:id", "HTTP methods mapping: GET, POST, PUT, DELETE", "Status codes: 200, 201, 400, 404, 500", "Request/Response format: JSON structure", "Pagination, sorting, filtering for collection endpoints"],
    "explanationId": "### Resource Naming\nNama resource plural (/products), nested (/products/123/reviews).\n\n### HTTP Methods\nGET baca, POST buat, PUT update, DELETE hapus.\n\n### Status Codes\n200 OK, 201 Created, 400 Bad Request, 404 Not Found, 500 Server Error.\n\n### Response Format\nKonsisten: { status, data, message }.",
    "explanationEn": "### Resource Naming\nPlural resources, nested resources.\n\n### HTTP Methods\nCRUD mapping.\n\n### Status Codes\nCommon HTTP status codes.\n\n### Response Format\nConsistent JSON structure.",
    "experimentsId": ["Buat nested resource: /users/:id/orders", "Implementasikan pagination dengan query ?page=1&limit=10", "Buat standardized error response format", "Tambah HATEOAS links di response"],
    "experimentsEn": ["Create nested resource: /users/:id/orders", "Implement pagination with query ?page=1&limit=10", "Create standardized error response format", "Add HATEOAS links in response"],
    "challengeId": "Buat REST API lengkap untuk E-Commerce: products, categories, orders dengan pagination dan filtering.",
    "challengeEn": "Build a complete REST API for E-Commerce: products, categories, orders with pagination and filtering.",
    "summaryId": "Minggu 6 dari 12: **REST API Design** (Level: Menengah). Minggu depan: **Authentication & Authorization**.",
    "summaryEn": "Week 6 of 12: **REST API Design** (Level: Intermediate). Next week: **Authentication & Authorization**."
  },
  {
    "week": 7, "level": "intermediate", "topicId": "auth",
    "titleId": "Authentication & Authorization", "titleEn": "Authentication & Authorization",
    "programId": "JWT Auth", "programEn": "JWT Auth",
    "levelNameId": "Menengah", "levelNameEn": "Intermediate",
    "language": "javascript",
    "code": "const crypto = require(\"crypto\");\n\nconsole.log(\"=== Password Hashing ===\");\nfunction hashPassword(password) {\n  const salt = crypto.randomBytes(16).toString(\"hex\");\n  const hash = crypto.pbkdf2Sync(password, salt, 1000, 64, \"sha512\").toString(\"hex\");\n  return salt + \":\" + hash;\n}\n\nfunction verifyPassword(password, stored) {\n  const [salt, hash] = stored.split(\":\");\n  const testHash = crypto.pbkdf2Sync(password, salt, 1000, 64, \"sha512\").toString(\"hex\");\n  return testHash === hash;\n}\n\nconst stored = hashPassword(\"rahasia123\");\nconsole.log(\"Stored:\", stored.substring(0, 40) + \"...\");\nconsole.log(\"Verify correct:\", verifyPassword(\"rahasia123\", stored));\nconsole.log(\"Verify wrong:\", verifyPassword(\"salah\", stored));\n\nconsole.log(\"\\n=== JWT Simulation ===\");\nfunction createJWT(payload, secret) {\n  const header = { alg: \"HS256\", typ: \"JWT\" };\n  const encode = (obj) => Buffer.from(JSON.stringify(obj)).toString(\"base64\");\n  const data = encode(header) + \".\" + encode(payload);\n  const signature = crypto.createHmac(\"sha256\", secret).update(data).digest(\"base64\");\n  return data + \".\" + signature;\n}\n\nconst token = createJWT({ userId: 1, role: \"admin\" }, \"secret-key\");\nconsole.log(\"Token:\", token.substring(0, 50) + \"...\");\n\nconsole.log(\"\\n=== Role-Based Access ===\");\nfunction checkPermission(userRole, requiredRole) {\n  const roles = { admin: 3, editor: 2, viewer: 1 };\n  return (roles[userRole] || 0) >= (roles[requiredRole] || 0);\n}\nconsole.log(\"Admin can edit:\", checkPermission(\"admin\", \"editor\"));\nconsole.log(\"Viewer can edit:\", checkPermission(\"viewer\", \"editor\"));",
    "objectivesId": ["Password hashing dengan bcrypt (salt + hash)", "JSON Web Tokens (JWT): header.payload.signature", "Middleware auth: verify token di setiap request", "Role-Based Access Control (RBAC)", "Session vs Token authentication"],
    "objectivesEn": ["Password hashing with bcrypt (salt + hash)", "JSON Web Tokens (JWT): header.payload.signature", "Auth middleware: verify token on every request", "Role-Based Access Control (RBAC)", "Session vs Token authentication"],
    "explanationId": "### Password Hashing\nBcrypt: salt + hash. Never store plain password.\n\n### JWT\nHeader (algorithm) + Payload (claims) + Signature. Stateless auth.\n\n### RBAC\nRole hierarchy: admin > editor > viewer.\n\n### Middleware\nverifyToken middleware sebelum route handler.",
    "explanationEn": "### Password Hashing\nBcrypt with salt.\n\n### JWT\nHeader + Payload + Signature.\n\n### RBAC\nRole-based access control.\n\n### Middleware\nAuth middleware pattern.",
    "experimentsId": ["Buat register dan login flow lengkap", "Implementasikan refresh token mechanism", "Tambah middleware untuk role checking", "Buat password reset flow"],
    "experimentsEn": ["Create complete register and login flow", "Implement refresh token mechanism", "Add middleware for role checking", "Create password reset flow"],
    "challengeId": "Buat sistem auth lengkap: register, login, JWT, role-based access, password hashing.",
    "challengeEn": "Build a complete auth system: register, login, JWT, role-based access, password hashing.",
    "summaryId": "Minggu 7 dari 12: **Authentication & Authorization** (Level: Menengah). Minggu depan: **Database & ORM**.",
    "summaryEn": "Week 7 of 12: **Authentication & Authorization** (Level: Intermediate). Next week: **Database & ORM**."
  },
  {
    "week": 8, "level": "intermediate", "topicId": "database",
    "titleId": "Database & ORM", "titleEn": "Database & ORM",
    "programId": "Data Access Layer", "programEn": "Data Access Layer",
    "levelNameId": "Menengah", "levelNameEn": "Intermediate",
    "language": "javascript",
    "code": "console.log(\"=== Database Simulation ===\");\n\nconst users = [\n  { id: 1, nama: \"Budi\", email: \"budi@mail.com\", umur: 25 },\n  { id: 2, nama: \"Siti\", email: \"siti@mail.com\", umur: 23 },\n  { id: 3, nama: \"Andi\", email: \"andi@mail.com\", umur: 30 },\n];\n\nconst UserModel = {\n  findAll: () => users,\n  findById: (id) => users.find(u => u.id === id),\n  create: (data) => { const u = { id: users.length + 1, ...data }; users.push(u); return u; },\n  update: (id, data) => { const i = users.findIndex(u => u.id === id); if (i >= 0) Object.assign(users[i], data); return users[i]; },\n  delete: (id) => { const i = users.findIndex(u => u.id === id); if (i >= 0) users.splice(i, 1); return i >= 0; },\n  where: (key, val) => users.filter(u => u[key] === val),\n};\n\nconsole.log(\"All users:\", UserModel.findAll().length);\nconsole.log(\"Find id=1:\", UserModel.findById(1).nama);\nconsole.log(\"Create:\", UserModel.create({ nama: \"Dewi\", email: \"dewi@mail.com\", umur: 27 }));\nconsole.log(\"Update:\", UserModel.update(1, { umur: 26 }));\nconsole.log(\"Where umur=30:\", UserModel.where(\"umur\", 30).map(u => u.nama));\nconsole.log(\"Delete:\", UserModel.delete(2));\nconsole.log(\"Final count:\", UserModel.findAll().length);\n\nconsole.log(\"\\n=== SQL Queries ===\");\nconst queries = [\n  \"SELECT * FROM users\",\n  \"SELECT * FROM users WHERE umur > 25\",\n  \"INSERT INTO users (nama, email) VALUES ('Dewi', 'dewi@mail.com')\",\n  \"UPDATE users SET umur = 26 WHERE id = 1\",\n  \"DELETE FROM users WHERE id = 2\",\n];\nfor (const q of queries) console.log(\"  \" + q);",
    "objectivesId": ["CRUD operations: Create, Read, Update, Delete", "SQL dasar: SELECT, INSERT, UPDATE, DELETE", "ORM pattern: Model sebagai abstraction layer", "Relationships: one-to-many, many-to-many", "Migrations dan schema management"],
    "objectivesEn": ["CRUD operations: Create, Read, Update, Delete", "SQL basics: SELECT, INSERT, UPDATE, DELETE", "ORM pattern: Model as abstraction layer", "Relationships: one-to-many, many-to-many", "Migrations and schema management"],
    "explanationId": "### CRUD\nCreate (INSERT), Read (SELECT), Update (UPDATE), Delete (DELETE).\n\n### ORM\nObject-Relational Mapping: table menjadi Model class.\n\n### Relationships\nOne-to-many (User has many Posts), Many-to-many (Users <-> Roles).\n\n### Migrations\nVersion control untuk database schema.",
    "explanationEn": "### CRUD\nCreate, Read, Update, Delete operations.\n\n### ORM\nModels as abstraction over tables.\n\n### Relationships\nOne-to-many, many-to-many.\n\n### Migrations\nDatabase schema versioning.",
    "experimentsId": ["Buat model Post dengan relasi ke User", "Implementasikan pagination di findAll", "Tambah search/filter dengan where clause", "Buat seeding data untuk development"],
    "experimentsEn": ["Create Post model with User relation", "Implement pagination in findAll", "Add search/filter with where clause", "Create data seeding for development"],
    "challengeId": "Buat blog API dengan User, Post, Comment models. Implementasikan CRUD dan relationships.",
    "challengeEn": "Build a blog API with User, Post, Comment models. Implement CRUD and relationships.",
    "summaryId": "Minggu 8 dari 12: **Database & ORM** (Level: Menengah). Selesai fase Intermediate! Minggu depan: **Testing** (Advanced).",
    "summaryEn": "Week 8 of 12: **Database & ORM** (Level: Intermediate). Intermediate phase complete! Next week: **Testing** (Advanced)."
  },
  {
    "week": 9, "level": "advanced", "topicId": "testing",
    "titleId": "Testing & Quality", "titleEn": "Testing & Quality",
    "programId": "Unit Test", "programEn": "Unit Test",
    "levelNameId": "Lanjutan", "levelNameEn": "Advanced",
    "language": "javascript",
    "code": "console.log(\"=== Testing Simulation ===\");\n\nfunction tambah(a, b) { return a + b; }\nfunction bagi(a, b) { if (b === 0) throw new Error(\"Nol!\"); return a / b; }\nfunction kali(a, b) { return a * b; }\n\nfunction assertEqual(actual, expected, testName) {\n  if (actual === expected) {\n    console.log(\"  PASS: \" + testName);\n    return true;\n  } else {\n    console.log(\"  FAIL: \" + testName + \" (expected \" + expected + \", got \" + actual + \")\");\n    return false;\n  }\n}\n\nconsole.log(\"\\nTest tambah:\");\nassertEqual(tambah(2, 3), 5, \"2 + 3 = 5\");\nassertEqual(tambah(-1, 1), 0, \"-1 + 1 = 0\");\nassertEqual(tambah(0, 0), 0, \"0 + 0 = 0\");\n\nconsole.log(\"\\nTest bagi:\");\nassertEqual(bagi(10, 2), 5, \"10 / 2 = 5\");\nassertEqual(bagi(7, 2), 3.5, \"7 / 2 = 3.5\");\ntry {\n  bagi(5, 0);\n  console.log(\"  FAIL: should throw\");\n} catch (e) {\n  console.log(\"  PASS: throws on zero\");\n}\n\nconsole.log(\"\\nTest kali:\");\nassertEqual(kali(3, 4), 12, \"3 x 4 = 12\");\nassertEqual(kali(-2, 3), -6, \"-2 x 3 = -6\");\nassertEqual(kali(0, 100), 0, \"0 x 100 = 0\");\n\nconsole.log(\"\\n=== Mock Pattern ===\");\nfunction fetchData(api) {\n  return api.get(\"/data\");\n}\nconst mockApi = { get: (url) => ({ data: \"mock response from \" + url }) };\nconsole.log(\"Mock result:\", fetchData(mockApi));",
    "objectivesId": ["Unit testing: test individual functions", "Test framework: Jest, Mocha, Vitest", "Assertion: toEqual, toBe, toThrow", "Mock dan stub untuk isolation", "Test coverage dan integration testing"],
    "objectivesEn": ["Unit testing: test individual functions", "Test frameworks: Jest, Mocha, Vitest", "Assertions: toEqual, toBe, toThrow", "Mock and stub for isolation", "Test coverage and integration testing"],
    "explanationId": "### Unit Test\nTest function secara isolated. Arrange, Act, Assert.\n\n### Jest\ntest(\"name\", () => { expect(fn()).toEqual(value) }).\n\n### Mock\nSimulasi dependency (API, database) dengan mock object.\n\n### Coverage\nnpm test -- --coverage untuk lihat coverage.",
    "explanationEn": "### Unit Tests\nTest individual functions in isolation.\n\n### Jest\ntest() and expect() API.\n\n### Mocks\nSimulate dependencies.\n\n### Coverage\nMeasure code coverage.",
    "experimentsId": ["Buat test untuk edge cases: negative numbers, empty arrays", "Implementasikan mock untuk API call", "Buat integration test untuk Express route", "Tambah test coverage report"],
    "experimentsEn": ["Create tests for edge cases", "Implement mock for API call", "Create integration test for Express route", "Add test coverage report"],
    "challengeId": "Buat test suite lengkap untuk REST API: unit test, integration test, mock database.",
    "challengeEn": "Build a complete test suite for REST API: unit tests, integration tests, mock database.",
    "summaryId": "Minggu 9 dari 12: **Testing & Quality** (Level: Lanjutan). Minggu depan: **Performance & Security**.",
    "summaryEn": "Week 9 of 12: **Testing & Quality** (Level: Advanced). Next week: **Performance & Security**."
  },
  {
    "week": 10, "level": "advanced", "topicId": "performance",
    "titleId": "Performance & Security", "titleEn": "Performance & Security",
    "programId": "Optimasi", "programEn": "Optimization",
    "levelNameId": "Lanjutan", "levelNameEn": "Advanced",
    "language": "javascript",
    "code": "console.log(\"=== Performance Tips ===\");\n\nconsole.log(\"\\n1. Cluster Mode:\");\nconsole.log(\"  const cluster = require('cluster');\");\nconsole.log(\"  if (cluster.isMaster) { fork workers }\");\n\nconsole.log(\"\\n2. Caching:\");\nconst cache = new Map();\nfunction getCached(key, fetchFn) {\n  if (cache.has(key)) { console.log(\"  Cache hit:\", key); return cache.get(key); }\n  const val = fetchFn();\n  cache.set(key, val);\n  console.log(\"  Cache miss, stored:\", key);\n  return val;\n}\ngetCached(\"user:1\", () => ({ id: 1, nama: \"Budi\" }));\ngetCached(\"user:1\", () => ({ id: 1, nama: \"Budi\" }));\n\nconsole.log(\"\\n3. Streaming:\");\nconsole.log(\"  fs.createReadStream('large.txt').pipe(res)\");\n\nconsole.log(\"\\n=== Security Best Practices ===\");\nconst security = [\n  \"helmet() - set security headers\",\n  \"cors() - configure allowed origins\",\n  \"express-rate-limit - prevent brute force\",\n  \"express-validator - input sanitization\",\n  \"dotenv - store secrets in .env\",\n];\nfor (const s of security) console.log(\"  - \" + s);\n\nconsole.log(\"\\n=== Environment Config ===\");\nconsole.log(\"  NODE_ENV=production\");\nconsole.log(\"  PORT=3000\");\nconsole.log(\"  DATABASE_URL=postgres://...\");\nconsole.log(\"  JWT_SECRET=use-random-256-bit\");",
    "objectivesId": ["Cluster mode untuk multi-core", "Caching: Redis, in-memory cache", "Streaming untuk file besar", "Security: helmet, CORS, rate limiting", "Environment configuration dan secrets management"],
    "objectivesEn": ["Cluster mode for multi-core", "Caching: Redis, in-memory cache", "Streaming for large files", "Security: helmet, CORS, rate limiting", "Environment configuration and secrets management"],
    "explanationId": "### Cluster\nNode.js single-thread. Cluster untuk gunakan semua core.\n\n### Caching\nCache frequent queries. TTL untuk expiration.\n\n### Streaming\nBaca file chunk-by-chunk, tidak load seluruh ke memory.\n\n### Security\nHelmet (headers), CORS (origin), Rate Limiter (brute force).",
    "explanationEn": "### Cluster\nUtilize all CPU cores.\n\n### Caching\nCache with TTL.\n\n### Streaming\nMemory-efficient file processing.\n\n### Security\nHeaders, CORS, rate limiting.",
    "experimentsId": ["Implementasikan Redis cache", "Buat streaming file upload", "Tambah rate limiting middleware", "Setup helmet dan CORS di Express"],
    "experimentsEn": ["Implement Redis cache", "Create streaming file upload", "Add rate limiting middleware", "Setup helmet and CORS in Express"],
    "challengeId": "Optimasi API: tambah caching, streaming download, security headers, rate limiting.",
    "challengeEn": "Optimize API: add caching, streaming download, security headers, rate limiting.",
    "summaryId": "Minggu 10 dari 12: **Performance & Security** (Level: Lanjutan). Minggu depan: **Deployment & DevOps**.",
    "summaryEn": "Week 10 of 12: **Performance & Security** (Level: Advanced). Next week: **Deployment & DevOps**."
  },
  {
    "week": 11, "level": "advanced", "topicId": "deployment",
    "titleId": "Deployment & DevOps", "titleEn": "Deployment & DevOps",
    "programId": "CI/CD Pipeline", "programEn": "CI/CD Pipeline",
    "levelNameId": "Lanjutan", "levelNameEn": "Advanced",
    "language": "javascript",
    "code": "console.log(\"=== Deployment Strategies ===\");\n\nconsole.log(\"\\n1. Docker:\");\nconsole.log(\"  FROM node:18-alpine\");\nconsole.log(\"  WORKDIR /app\");\nconsole.log(\"  COPY package*.json ./\");\nconsole.log(\"  RUN npm ci --production\");\nconsole.log(\"  COPY . .\");\nconsole.log(\"  EXPOSE 3000\");\nconsole.log(\"  CMD ['node', 'server.js']\");\n\nconsole.log(\"\\n2. Environment Variables:\");\nconsole.log(\"  NODE_ENV=production\");\nconsole.log(\"  npm ci (bukan npm install)\");\nconsole.log(\"  process.env.PORT || 3000\");\n\nconsole.log(\"\\n3. CI/CD Pipeline:\");\nconsole.log(\"  1. Push to main branch\");\nconsole.log(\"  2. Run tests (npm test)\");\nconsole.log(\"  3. Build Docker image\");\nconsole.log(\"  4. Push to registry\");\nconsole.log(\"  5. Deploy to production\");\n\nconsole.log(\"\\n4. Process Manager:\");\nconsole.log(\"  pm2 start server.js -i max\");\nconsole.log(\"  pm2 monit\");\nconsole.log(\"  pm2 logs\");\n\nconsole.log(\"\\n5. Health Check:\");\nconsole.log(\"  GET /health -> { status: 'ok', uptime: process.uptime() }\");\n\nconsole.log(\"\\n=== Monitoring ===\");\nconsole.log(\"  - Logging: Winston, Pino\");\nconsole.log(\"  - APM: New Relic, DataDog\");\nconsole.log(\"  - Uptime: Pingdom, UptimeRobot\");",
    "objectivesId": ["Docker: containerize aplikasi Node.js", "CI/CD pipeline: GitHub Actions, GitLab CI", "Process manager: PM2, Docker Compose", "Environment: production config, secrets", "Monitoring: logging, APM, health checks"],
    "objectivesEn": ["Docker: containerize Node.js applications", "CI/CD pipeline: GitHub Actions, GitLab CI", "Process manager: PM2, Docker Compose", "Environment: production config, secrets", "Monitoring: logging, APM, health checks"],
    "explanationId": "### Docker\nMulti-stage build, alpine image, npm ci untuk reproducible.\n\n### CI/CD\nAutomated test -> build -> deploy.\n\n### PM2\nProcess manager dengan load balancing (cluster mode).\n\n### Health Check\nEndpoint untuk monitoring uptime dan status.",
    "explanationEn": "### Docker\nMulti-stage builds with Alpine.\n\n### CI/CD\nAutomated pipelines.\n\n### PM2\nProcess management.\n\n### Health Checks\nUptime monitoring.",
    "experimentsId": ["Buat Dockerfile dengan multi-stage build", "Setup GitHub Actions workflow", "Implementasikan health check endpoint", "Setup Winston logging"],
    "experimentsEn": ["Create Dockerfile with multi-stage build", "Setup GitHub Actions workflow", "Implement health check endpoint", "Setup Winston logging"],
    "challengeId": "Deploy aplikasi Node.js ke cloud: Dockerize, setup CI/CD, monitoring, dan auto-scaling.",
    "challengeEn": "Deploy Node.js app to cloud: Dockerize, setup CI/CD, monitoring, and auto-scaling.",
    "summaryId": "Minggu 11 dari 12: **Deployment & DevOps** (Level: Lanjutan). Minggu depan: **Capstone Project**!",
    "summaryEn": "Week 11 of 12: **Deployment & DevOps** (Level: Advanced). Next week: **Capstone Project**!"
  },
  {
    "week": 12, "level": "advanced", "topicId": "capstone",
    "titleId": "Capstone: Full-Stack API", "titleEn": "Capstone: Full-Stack API",
    "programId": "E-Commerce API", "programEn": "E-Commerce API",
    "levelNameId": "Lanjutan", "levelNameEn": "Advanced",
    "language": "javascript",
    "code": "console.log(\"=== Capstone: E-Commerce API ===\");\nconsole.log(\"Menggabungkan semua konsep: Express, JWT, Database, Testing, Docker\");\nconsole.log(\"\");\n\nconst app = {\n  name: \"E-Commerce API\",\n  version: \"1.0.0\",\n  features: [\n    \"User registration & login (JWT)\",\n    \"Product catalog (CRUD)\",\n    \"Shopping cart\",\n    \"Order management\",\n    \"Role-based access (admin, customer)\",\n    \"Pagination & filtering\",\n    \"Input validation\",\n    \"Error handling\",\n    \"Unit & integration tests\",\n    \"Docker deployment\",\n  ],\n};\n\nconsole.log(\"Features:\");\nfor (const f of app.features) console.log(\"  - \" + f);\n\nconsole.log(\"\\n=== Architecture ===\");\nconsole.log(\"Routes -> Controllers -> Services -> Models -> Database\");\nconsole.log(\"\");\nconsole.log(\"Routes:    /api/v1/users, /api/v1/products, /api/v1/orders\");\nconsole.log(\"Controllers: Handle request/response\");\nconsole.log(\"Services:  Business logic\");\nconsole.log(\"Models:    Data access layer\");\n\nconsole.log(\"\\n=== API Endpoints ===\");\nconst endpoints = [\n  { method: \"POST\", path: \"/api/v1/auth/register\", desc: \"Register new user\" },\n  { method: \"POST\", path: \"/api/v1/auth/login\", desc: \"Login, get JWT\" },\n  { method: \"GET\", path: \"/api/v1/products\", desc: \"List products (paginated)\" },\n  { method: \"POST\", path: \"/api/v1/orders\", desc: \"Create order (auth)\" },\n  { method: \"GET\", path: \"/api/v1/orders/:id\", desc: \"Get order detail (auth)\" },\n];\nfor (const e of endpoints) console.log(\"  \" + e.method + \" \" + e.path + \" -> \" + e.desc);\n\nconsole.log(\"\\n=== Project Structure ===\");\nconsole.log(\"  src/\");\nconsole.log(\"    controllers/\");\nconsole.log(\"    services/\");\nconsole.log(\"    models/\");\nconsole.log(\"    middleware/\");\nconsole.log(\"    routes/\");\nconsole.log(\"    config/\");\nconsole.log(\"    utils/\");\nconsole.log(\"  tests/\");\nconsole.log(\"  Dockerfile\");",
    "objectivesId": ["Menggabungkan semua konsep: Express, JWT, Database, Testing", "Arsitektur berlapis: Routes -> Controllers -> Services -> Models", "API versioning: /api/v1/resources", "Comprehensive testing: unit, integration, e2e", "Deployment: Docker, CI/CD, monitoring"],
    "objectivesEn": ["Combine all concepts: Express, JWT, Database, Testing", "Layered architecture: Routes -> Controllers -> Services -> Models", "API versioning: /api/v1/resources", "Comprehensive testing: unit, integration, e2e", "Deployment: Docker, CI/CD, monitoring"],
    "explanationId": "### Arsitektur Berlapis\nRoutes (definisikan endpoint) -> Controllers (handle HTTP) -> Services (business logic) -> Models (data access).\n\n### API Versioning\n/api/v1/ untuk backward compatibility.\n\n### Testing Pyramid\nUnit tests (banyak) > Integration tests > E2E tests (sedikit).\n\n### Deployment\nDocker container, CI/CD pipeline, monitoring dengan PM2/APM.",
    "explanationEn": "### Layered Architecture\nRoutes -> Controllers -> Services -> Models.\n\n### API Versioning\n/api/v1/ for compatibility.\n\n### Testing Pyramid\nUnit > Integration > E2E.\n\n### Deployment\nDocker, CI/CD, monitoring.",
    "experimentsId": ["Tambah fitur: product reviews dan ratings", "Implementasikan caching dengan Redis", "Buat WebSocket untuk real-time notifications", "Tambah file upload untuk product images"],
    "experimentsEn": ["Add product reviews and ratings", "Implement caching with Redis", "Create WebSocket for real-time notifications", "Add file upload for product images"],
    "challengeId": "Buat E-Commerce API lengkap: auth, products, cart, orders, tests, Docker. Production-ready!",
    "challengeEn": "Build a complete E-Commerce API: auth, products, cart, orders, tests, Docker. Production-ready!",
    "summaryId": "Minggu 12 dari 12: **Capstone: Full-Stack API** (Level: Lanjutan). Selesai! Anda sudah menguasai Node.js dari nol hingga production-ready.",
    "summaryEn": "Week 12 of 12: **Capstone: Full-Stack API** (Level: Advanced). Complete! You've mastered Node.js from scratch to production-ready."
  }
]

create_generator_file('nodejs', 'Node.js', LEVELS, MODULES)
