import { BaseGenerator } from './lib/base-generator.mjs';

const gen = new BaseGenerator('python', 'Python');

const LEVELS = [
  { levelId: 'beginer', nameId: 'Pemula', nameEn: 'Beginner', descId: 'Dasar Python: syntax, types, control flow, functions.', descEn: 'Python basics: syntax, types, control flow, functions.' },
  { levelId: 'intermediate', nameId: 'Menengah', nameEn: 'Intermediate', descId: 'Collections, OOP, File I/O, Error Handling.', descEn: 'Collections, OOP, File I/O, Error Handling.' },
  { levelId: 'advanced', nameId: 'Lanjutan', nameEn: 'Advanced', descId: 'Libraries, Testing, CLI, Project.', descEn: 'Libraries, Testing, CLI, Project.' }
];

const MODULES = [
  { week: 1, level: 'beginer', topicId: 'dasar-python', titleId: 'Dasar Python & Sintaks', titleEn: 'Python Basics & Syntax', programId: 'Halo Python', programEn: 'Hello Python', levelNameId: 'Pemula', levelNameEn: 'Beginner', language: 'python',
    code: '# Dasar Python & Sintaks\nnama = "Python"\nversi = "3.12"\nprint(f"Selamat datang di {nama}!")\nprint(f"Versi: {versi}")\n\numur = 25\ntinggi = 175.5\naktif = True\nhobi = ["ngoding", "baca buku", "musik"]\nprofil = {"nama": "Budi", "kota": "Jakarta"}\n\nprint(f"Umur: {umur} tahun")\nprint(f"Hobi: {\', \'.join(hobi)}")\nprint(f"Profil: {profil[\'nama\']} dari {profil[\'kota\']}")\n\ndef sapa(nama):\n    return f"Halo, {nama}!"\n\nkali = lambda a, b: a * b\n\nprint(sapa("Gopher"))\nprint(f"5 x 3 = {kali(5, 3)}")',
    objectivesId: ['Memahami Python sebagai bahasa interpreted', 'Menjalankan file Python dengan python command', 'Variabel: tidak perlu deklarasi tipe', 'Tipe data dasar: int, float, str, bool, list, dict', 'Function dengan def dan lambda'],
    objectivesEn: ['Understand Python as an interpreted language', 'Run Python files with the python command', 'Variables: no type declaration needed', 'Basic types: int, float, str, bool, list, dict', 'Functions with def and lambda'],
    explanationId: '### Apa Itu Python\nPython adalah bahasa interpreted, dynamically typed.\n\n### Variabel\nTidak perlu deklarasi tipe: x = 5 (otomatis int).\n\n### Tipe Data\nint, float, str, bool, list, dict, tuple, set.\n\n### Function\ndef nama(params): body.\n\n### f-strings\nf"Hello {name}" untuk string formatting.',
    explanationEn: '### What is Python\nInterpreted, dynamically typed language.\n\n### Variables\nNo type declaration needed.\n\n### Data Types\nint, float, str, bool, list, dict.\n\n### Functions\ndef and lambda.\n\n### f-strings\nModern string formatting.',
    experimentsId: ['Ubah nilai variabel', 'Tambah function baru', 'Coba tipe data tuple dan set', 'Buat lambda function'],
    experimentsEn: ['Change variable values', 'Add a new function', 'Try tuple and set', 'Create lambda'],
    challengeId: 'Buat program kalkulator dengan function.',
    challengeEn: 'Build a calculator with functions.',
    summaryId: 'Minggu 1 dari 12: **Dasar Python & Sintaks** (Level: Pemula).',
    summaryEn: 'Week 1 of 12: **Python Basics & Syntax** (Level: Beginner).' },

  { week: 2, level: 'beginer', topicId: 'control-flow', titleId: 'Control Flow & Loops', titleEn: 'Control Flow & Loops', programId: 'Grade & Angka', programEn: 'Grades & Numbers', levelNameId: 'Pemula', levelNameEn: 'Beginner', language: 'python',
    code: '# Control Flow & Loops\nnama = "Budi"\numur = 25\n\nif umur >= 18:\n    print(f"{nama} sudah dewasa")\nelif umur >= 13:\n    print(f"{nama} remaja")\nelse:\n    print(f"{nama} anak-anak")\n\nnilai = 85\nif nilai >= 90: grade = "A"\nelif nilai >= 75: grade = "B"\nelif nilai >= 60: grade = "C"\nelse: grade = "D"\nprint(f"Nilai {nilai} = Grade {grade}")\n\nprint("For loop:")\nfor i in range(1, 6): print(f"  {i}", end="")\nprint()\n\nbuah = ["apel", "mangga", "pisang"]\nfor i, item in enumerate(buah):\n    print(f"  {i+1}. {item}")\n\nangka = [x**2 for x in range(1, 6)]\nprint(f"Kuadrat: {angka}")',
    objectivesId: ['If/elif/else untuk kondisi', 'For loop dengan range dan list', 'While loop dengan kondisi', 'Break, continue, pass', 'List comprehension'],
    objectivesEn: ['If/elif/else for conditions', 'For loop with range and lists', 'While loop with conditions', 'Break, continue, pass', 'List comprehension'],
    explanationId: '### If/Else\nIndentasi menentukan block (4 spaces).\n\n### For Loop\nfor item in iterable. range(n) untuk angka 0..n-1.\n\n### Comprehension\n[x**2 for x in range(5)] inline loop.',
    explanationEn: '### If/Else\nIndentation defines blocks.\n\n### For Loop\nIterate over iterables.\n\n### Comprehension\nInline loop for creating lists.',
    experimentsId: ['Ubah nilai lihat grade', 'Buat nested loop', 'Coba list comprehension dengan if', 'FizzBuzz'],
    experimentsEn: ['Change values', 'Create nested loop', 'Try list comprehension with if', 'FizzBuzz'],
    challengeId: 'Buat program konversi suhu dengan menu.',
    challengeEn: 'Build temperature converter with menu.',
    summaryId: 'Minggu 2 dari 12: **Control Flow & Loops** (Level: Pemula).',
    summaryEn: 'Week 2 of 12: **Control Flow & Loops** (Level: Beginner).' },

  { week: 3, level: 'beginer', topicId: 'functions', titleId: 'Functions & Modules', titleEn: 'Functions & Modules', programId: 'Kalkulator', programEn: 'Calculator', levelNameId: 'Pemula', levelNameEn: 'Beginner', language: 'python',
    code: '# Functions & Modules\nimport math\nimport random\n\ndef tambah(a, b): return a + b\ndef bagi(a, b):\n    if b == 0: raise ValueError("Tidak bisa bagi nol")\n    return a / b\ndef hitung(*args): return sum(args) / len(args) if args else 0\ndef buat_profil(**kwargs): return kwargs\n\nprint(f"10 + 5 = {tambah(10, 5)}")\nprint(f"10 / 3 = {bagi(10, 3):.2f}")\nprint(f"Rata-rata: {hitung(10, 20, 30):.1f}")\n\nprint(f"\\nPi: {math.pi}")\nprint(f"Sqrt(16): {math.sqrt(16)}")\nprint(f"Random: {random.randint(1, 100)}")',
    objectivesId: ['Function: def, parameter, return', 'Default parameter dan keyword arguments', '*args dan **kwargs', 'Import module: import, from ... import', 'Built-in modules: math, random'],
    objectivesEn: ['Functions: def, parameters, return', 'Default parameters and keyword arguments', '*args and **kwargs', 'Import modules: import, from ... import', 'Built-in modules: math, random'],
    explanationId: '### Function\ndef nama(params): return value.\n\n### *args & **kwargs\n*args terima positional args, **kwargs terima keyword args.\n\n### Import\nimport module, from module import function.\n\n### Built-in Modules\nmath, random, os, datetime.',
    explanationEn: '### Functions\ndef and return.\n\n### *args & **kwargs\nVariable arguments.\n\n### Import\nModule imports.\n\n### Built-in Modules\nmath, random, os.',
    experimentsId: ['Buat function rekursif faktorial', 'Coba **kwargs', 'Buat module sendiri', 'Decorator sederhana'],
    experimentsEn: ['Create recursive factorial', 'Try **kwargs', 'Create your own module', 'Simple decorator'],
    challengeId: 'Buat module utils: kalkulator, converter, validator.',
    challengeEn: 'Build utils module: calculator, converter, validator.',
    summaryId: 'Minggu 3 dari 12: **Functions & Modules** (Level: Pemula).',
    summaryEn: 'Week 3 of 12: **Functions & Modules** (Level: Beginner).' },

  { week: 4, level: 'beginer', topicId: 'collections', titleId: 'Collections & Data Structures', titleEn: 'Collections & Data Structures', programId: 'Manajemen Data', programEn: 'Data Management', levelNameId: 'Pemula', levelNameEn: 'Beginner', language: 'python',
    code: '# Collections\nbuah = ["apel", "mangga", "pisang"]\nbuah.append("jeruk")\nprint(f"List: {buah}")\nprint(f"Slice: {buah[1:3]}")\n\nkoordinat = (10, 20)\nx, y = koordinat\nprint(f"Tuple: {koordinat}")\n\nmhs = {"nama": "Budi", "umur": 25}\nmhs["ipk"] = 3.85\nprint(f"Dict: {mhs}")\n\nangka = {1, 2, 3, 4, 5, 5, 3}\nprint(f"Set: {angka}")\nprint(f"Union: {angka | {4, 5, 6}}")',
    objectivesId: ['List: mutable, ordered collection', 'Tuple: immutable, ordered collection', 'Dict: key-value pairs', 'Set: unique elements', 'Nested data structures'],
    objectivesEn: ['List: mutable, ordered collection', 'Tuple: immutable, ordered collection', 'Dict: key-value pairs', 'Set: unique elements', 'Nested data structures'],
    explanationId: '### List\nMutable, ordered. append, insert, slice.\n\n### Tuple\nImmutable. x, y = (1, 2).\n\n### Dict\nKey-value pairs.\n\n### Set\nUnique elements. Union (|), intersection (&).',
    explanationEn: '### List\nMutable ordered collection.\n\n### Tuple\nImmutable ordered collection.\n\n### Dict\nKey-value pairs.\n\n### Set\nUnique elements with set operations.',
    experimentsId: ['CRUD pada list of dicts', 'Stack dengan list', 'Dict comprehension', 'Frequency counter'],
    experimentsEn: ['CRUD on list of dicts', 'Stack with list', 'Dict comprehension', 'Frequency counter'],
    challengeId: 'Buat program inventory: tambah/hapus produk.',
    challengeEn: 'Build inventory program: add/remove products.',
    summaryId: 'Minggu 4 dari 12: **Collections** (Level: Pemula).',
    summaryEn: 'Week 4 of 12: **Collections** (Level: Beginner).' },

  { week: 5, level: 'intermediate', topicId: 'oop', titleId: 'Object-Oriented Programming', titleEn: 'Object-Oriented Programming', programId: 'Class & Object', programEn: 'Class & Object', levelNameId: 'Menengah', levelNameEn: 'Intermediate', language: 'python',
    code: '# OOP\nclass Produk:\n    def __init__(self, nama, harga, stok=0):\n        self.nama = nama\n        self.harga = harga\n        self.stok = stok\n    def info(self):\n        return f"{self.nama}: Rp{self.harga:,.0f} (stok: {self.stok})"\n    def diskon(self, persen):\n        self.harga -= self.harga * (persen / 100)\n\nlaptop = Produk("Laptop", 15000000, 10)\nprint(laptop.info())\nlaptop.diskon(10)\nprint(laptop.info())',
    objectivesId: ['Class dan Object: class, __init__, self', 'Instance methods', 'Inheritance dan super()', 'Encapsulation', 'Magic methods: __str__'],
    objectivesEn: ['Class and Object: class, __init__, self', 'Instance methods', 'Inheritance and super()', 'Encapsulation', 'Magic methods: __str__'],
    explanationId: '### Class\nBlueprint untuk object. __init__ constructor.\n\n### Inheritance\nChild inherit dari parent. super().\n\n### Encapsulation\nPublic, _protected, __private.',
    explanationEn: '### Class\nBlueprint for objects.\n\n### Inheritance\nChild inherits from parent.\n\n### Encapsulation\nAccess modifiers.',
    experimentsId: ['BankAccount class', 'Multiple inheritance', 'Property decorator', 'Abstract class'],
    experimentsEn: ['BankAccount class', 'Multiple inheritance', 'Property decorator', 'Abstract class'],
    challengeId: 'Buat sistem toko: Product, Cart, Customer.',
    challengeEn: 'Build store system: Product, Cart, Customer.',
    summaryId: 'Minggu 5 dari 12: **OOP** (Level: Menengah).',
    summaryEn: 'Week 5 of 12: **OOP** (Level: Intermediate).' },

  { week: 6, level: 'intermediate', topicId: 'file-io', titleId: 'File I/O & Error Handling', titleEn: 'File I/O & Error Handling', programId: 'File Manager', programEn: 'File Manager', levelNameId: 'Menengah', levelNameEn: 'Intermediate', language: 'python',
    code: '# File I/O & Error Handling\nimport json\nimport os\n\ndata = [{"nama": "Budi", "umur": 25}]\nwith open("data.json", "w") as f:\n    json.dump(data, f, indent=2)\n\ntry:\n    with open("data.json", "r") as f:\n        loaded = json.load(f)\n    print(f"Read: {len(loaded)} records")\nexcept FileNotFoundError:\n    print("File not found")\nexcept json.JSONDecodeError:\n    print("Invalid JSON")\n\ndef bagi(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return None\n    finally:\n        print("  cleanup")\n\nprint(f"10/2 = {bagi(10, 2)}")\nif os.path.exists("data.json"): os.remove("data.json")',
    objectivesId: ['File I/O: open, read, write', 'Context manager: with statement', 'JSON: json.dump, json.load', 'Error handling: try, except, finally', 'Custom exceptions'],
    objectivesEn: ['File I/O: open, read, write', 'Context manager: with statement', 'JSON: json.dump, json.load', 'Error handling: try, except, finally', 'Custom exceptions'],
    explanationId: '### File I/O\nopen() dengan mode: r, w, a. with untuk auto-close.\n\n### JSON\njson.dump(obj, file), json.load(file).\n\n### Error Handling\ntry: code, except Error: handler.',
    explanationEn: '### File I/O\nopen() with modes.\n\n### JSON\nSerialize and deserialize.\n\n### Error Handling\ntry/except/finally.',
    experimentsId: ['CSV reader/writer', 'Custom exception', 'Logging ke file', 'pathlib'],
    experimentsEn: ['CSV reader/writer', 'Custom exception', 'File logging', 'pathlib'],
    challengeId: 'Buat program manajemen kontak: read/write CSV.',
    challengeEn: 'Build contact manager: read/write CSV.',
    summaryId: 'Minggu 6 dari 12: **File I/O** (Level: Menengah).',
    summaryEn: 'Week 6 of 12: **File I/O** (Level: Intermediate).' },

  { week: 7, level: 'intermediate', topicId: 'libraries', titleId: 'Libraries & Virtual Environment', titleEn: 'Libraries & Virtual Environment', programId: 'PIP &venv', programEn: 'PIP &venv', levelNameId: 'Menengah', levelNameEn: 'Intermediate', language: 'python',
    code: '# Libraries\nfrom datetime import datetime, timedelta\nfrom collections import Counter, defaultdict\nimport itertools\n\nnow = datetime.now()\nprint(f"Sekarang: {now.strftime(\'%Y-%m-%d %H:%M:%S\')}")\n\nwords = ["apel", "mangga", "apel", "pisang"]\nfreq = Counter(words)\nprint(f"Frequency: {freq.most_common(2)}")\n\ngroups = defaultdict(list)\nfor word in words:\n    groups[len(word)].append(word)\nprint(f"Groups: {dict(groups)}")',
    objectivesId: ['Virtual environment: venv', 'Package management: pip', 'Standard library: datetime, collections', 'Third-party packages: requests', 'Import patterns'],
    objectivesEn: ['Virtual environment: venv', 'Package management: pip', 'Standard library: datetime, collections', 'Third-party packages: requests', 'Import patterns'],
    explanationId: '### venv\npython -m venv env && source env/bin/activate.\n\n### pip\npip install pkg, pip freeze > requirements.txt.\n\n### Standard Library\nos, sys, datetime, collections, itertools.',
    explanationEn: '### venv\nIsolated Python environments.\n\n### pip\nPackage management.\n\n### Standard Library\nBuilt-in modules.',
    experimentsId: ['Buat venv dan install packages', 'Counter frequency analysis', 'requirements.txt', 'requests HTTP call'],
    experimentsEn: ['Create venv and install', 'Counter analysis', 'requirements.txt', 'requests HTTP call'],
    challengeId: 'Buat project dengan venv: install packages, requirements.txt.',
    challengeEn: 'Build project with venv: install packages, requirements.txt.',
    summaryId: 'Minggu 7 dari 12: **Libraries** (Level: Menengah).',
    summaryEn: 'Week 7 of 12: **Libraries** (Level: Intermediate).' },

  { week: 8, level: 'intermediate', topicId: 'decorators-generators', titleId: 'Decorators & Generators', titleEn: 'Decorators & Generators', programId: 'Advanced Patterns', programEn: 'Advanced Patterns', levelNameId: 'Menengah', levelNameEn: 'Intermediate', language: 'python',
    code: '# Decorators & Generators\nimport functools\n\ndef timer(func):\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs)\n    return wrapper\n\n@timer\ndef hello():\n    print("Hello!")\n\nhello()\n\n# Generator\ndef fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b\n\nprint(f"Fibonacci: {list(fibonacci(10))}")\n\n# Generator expression\nkuadrat = (x**2 for x in range(5))\nprint(f"Kuadrat: {list(kuadrat)}")',
    objectivesId: ['Decorators: @decorator syntax', 'functools.wraps', 'Decorators dengan parameter', 'Generators: yield', 'Generator expressions'],
    objectivesEn: ['Decorators: @decorator syntax', 'functools.wraps', 'Decorators with parameters', 'Generators: yield', 'Generator expressions'],
    explanationId: '### Decorator\nFunction yang modify function lain. @decorator.\n\n### Generator\nyield untuk lazy evaluation.\n\n### Generator Expression\n(x**2 for x in range(10)).',
    explanationEn: '### Decorators\nModify functions.\n\n### Generators\nLazy evaluation with yield.\n\n### Generator Expressions\nLazy comprehensions.',
    experimentsId: ['Caching decorator', 'Retry decorator', 'File reading generator', 'Class-based decorator'],
    experimentsEn: ['Caching decorator', 'Retry decorator', 'File reading generator', 'Class-based decorator'],
    challengeId: 'Buat decorator library: timer, retry, cache.',
    challengeEn: 'Build decorator library: timer, retry, cache.',
    summaryId: 'Minggu 8 dari 12: **Decorators** (Level: Menengah).',
    summaryEn: 'Week 8 of 12: **Decorators** (Level: Intermediate).' },

  { week: 9, level: 'advanced', topicId: 'testing', titleId: 'Testing & Quality', titleEn: 'Testing & Quality', programId: 'Unit Test', programEn: 'Unit Test', levelNameId: 'Lanjutan', levelNameEn: 'Advanced', language: 'python',
    code: '# Testing\nimport unittest\n\ndef tambah(a, b): return a + b\ndef bagi(a, b):\n    if b == 0: raise ValueError("Nol!")\n    return a / b\n\nclass TestMath(unittest.TestCase):\n    def test_tambah(self):\n        self.assertEqual(tambah(2, 3), 5)\n        self.assertEqual(tambah(-1, 1), 0)\n    def test_bagi(self):\n        self.assertEqual(bagi(10, 2), 5)\n        with self.assertRaises(ValueError):\n            bagi(5, 0)\n\nif __name__ == "__main__":\n    print("Running tests...")\n    unittest.main(argv=[""], exit=False, verbosity=2)',
    objectivesId: ['unittest: TestCase, assert methods', 'pytest: simpler syntax', 'Mock dan patch', 'Test coverage: pytest-cov', 'TDD'],
    objectivesEn: ['unittest: TestCase, assert methods', 'pytest: simpler syntax', 'Mock and patch', 'Test coverage: pytest-cov', 'TDD'],
    explanationId: '### unittest\nclass TestX(unittest.TestCase): def test_method(self).\n\n### pytest\ndef test_function(): assert result == expected.\n\n### Coverage\npytest --cov=module.',
    explanationEn: '### unittest\nTest case classes.\n\n### pytest\nSimple test functions.\n\n### Coverage\nMeasure test coverage.',
    experimentsId: ['pytest fixtures', 'Mock API call', 'Parameterized tests', 'Integration tests'],
    experimentsEn: ['pytest fixtures', 'Mock API call', 'Parameterized tests', 'Integration tests'],
    challengeId: 'Buat test suite dengan 80%+ coverage.',
    challengeEn: 'Build test suite with 80%+ coverage.',
    summaryId: 'Minggu 9 dari 12: **Testing** (Level: Lanjutan).',
    summaryEn: 'Week 9 of 12: **Testing** (Level: Advanced).' },

  { week: 10, level: 'advanced', topicId: 'cli', titleId: 'CLI & Automation', titleEn: 'CLI & Automation', programId: 'Task CLI', programEn: 'Task CLI', levelNameId: 'Lanjutan', levelNameEn: 'Advanced', language: 'python',
    code: '# CLI & Automation\nimport argparse\nimport json\nimport os\n\nparser = argparse.ArgumentParser(description="Task Manager")\nparser.add_argument("action", choices=["add", "list", "done"])\nparser.add_argument("--title", "-t", help="Task title")\nparser.add_argument("--priority", "-p", default="medium")\n\nprint("CLI configured:")\nprint("  action: add, list, done")\nprint("  --title, --priority")\n\n# Task manager logic\ndef load_tasks():\n    if os.path.exists("tasks.json"):\n        with open("tasks.json") as f: return json.load(f)\n    return []\n\ndef save_tasks(tasks):\n    with open("tasks.json", "w") as f: json.dump(tasks, f)\n\ntasks = load_tasks()\nprint(f"Tasks: {len(tasks)}")',
    objectivesId: ['argparse untuk CLI arguments', 'Click library', 'File persistence: JSON', 'Automation: cron', 'Environment variables'],
    objectivesEn: ['argparse for CLI arguments', 'Click library', 'File persistence: JSON', 'Automation: cron', 'Environment variables'],
    explanationId: '### argparse\nparser.add_argument().\n\n### Click\n@click.command(), @click.option().\n\n### Automation\ncron atau Task Scheduler.',
    explanationEn: '### argparse\nCLI argument parsing.\n\n### Click\nDecorator-based CLI.\n\n### Automation\nScheduling scripts.',
    experimentsId: ['Click library', 'Rich output', 'Progress bar', 'Backup automation'],
    experimentsEn: ['Click library', 'Rich output', 'Progress bar', 'Backup automation'],
    challengeId: 'Buat Task CLI lengkap: add, list, done, delete.',
    challengeEn: 'Build complete Task CLI: add, list, done, delete.',
    summaryId: 'Minggu 10 dari 12: **CLI & Automation** (Level: Lanjutan).',
    summaryEn: 'Week 10 of 12: **CLI & Automation** (Level: Advanced).' },

  { week: 11, level: 'advanced', topicId: 'advanced-patterns', titleId: 'Advanced Patterns', titleEn: 'Advanced Patterns', programId: 'Design Patterns', programEn: 'Design Patterns', levelNameId: 'Lanjutan', levelNameEn: 'Advanced', language: 'python',
    code: '# Advanced Patterns\nfrom abc import ABC, abstractmethod\nfrom functools import lru_cache\n\n# Singleton\nclass Database:\n    _instance = None\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance\n\nprint(f"Singleton: {Database() is Database()}")\n\n# Factory\nclass Animal(ABC):\n    @abstractmethod\n    def speak(self): pass\n\nclass Dog(Animal):\n    def speak(self): return "Woof!"\n\nprint(f"Dog says: {Dog().speak()}")\n\n# Memoization\n@lru_cache(maxsize=128)\ndef fib(n):\n    if n < 2: return n\n    return fib(n-1) + fib(n-2)\n\nprint(f"fib(35): {fib(35)}")',
    objectivesId: ['Design patterns: Singleton, Factory', 'Abstract Base Classes', 'Memoization dan caching', 'Threading', 'Context managers'],
    objectivesEn: ['Design patterns: Singleton, Factory', 'Abstract Base Classes', 'Memoization and caching', 'Threading', 'Context managers'],
    explanationId: '### Singleton\nSatu instance saja. __new__ override.\n\n### Factory\nCreate object tanpa specify class.\n\n### Memoization\n@lru_cache untuk cache results.',
    explanationEn: '### Singleton\nSingle instance.\n\n### Factory\nObject creation abstraction.\n\n### Memoization\nCache results.',
    experimentsId: ['Strategy pattern', 'Thread-safe singleton', 'asyncio', 'Context manager'],
    experimentsEn: ['Strategy pattern', 'Thread-safe singleton', 'asyncio', 'Context manager'],
    challengeId: 'Buat event-driven system: Observer, async.',
    challengeEn: 'Build event-driven system: Observer, async.',
    summaryId: 'Minggu 11 dari 12: **Advanced Patterns** (Level: Lanjutan).',
    summaryEn: 'Week 11 of 12: **Advanced Patterns** (Level: Advanced).' },

  { week: 12, level: 'advanced', topicId: 'capstone', titleId: 'Capstone: Python Application', titleEn: 'Capstone: Python Application', programId: 'Task Manager Pro', programEn: 'Task Manager Pro', levelNameId: 'Lanjutan', levelNameEn: 'Advanced', language: 'python',
    code: '# Capstone: Task Manager Pro\nfrom datetime import datetime\nfrom collections import defaultdict\nimport json\n\nclass Task:\n    def __init__(self, title, priority="medium"):\n        self.title = title\n        self.priority = priority\n        self.done = False\n        self.created = datetime.now()\n    def complete(self): self.done = True\n    def to_dict(self): return {"title": self.title, "priority": self.priority, "done": self.done}\n\nclass TaskManager:\n    def __init__(self): self.tasks = []\n    def add(self, title, priority="medium"):\n        t = Task(title, priority)\n        self.tasks.append(t)\n        return t\n    def list_all(self): return self.tasks\n    def by_priority(self):\n        g = defaultdict(list)\n        for t in self.tasks: g[t.priority].append(t)\n        return dict(g)\n\ntm = TaskManager()\ntm.add("Learn Python", "high")\ntm.add("Build project", "high")\ntm.add("Write tests", "medium")\nprint(f"Tasks: {len(tm.list_all())}")\nfor p, tasks in tm.by_priority().items():\n    print(f"  {p}: {len(tasks)}")\n\nprint("\\nCapstone ready!")',
    objectivesId: ['Menggabungkan semua konsep', 'Professional project structure', 'CLI interface', 'Data persistence', 'Unit tests'],
    objectivesEn: ['Combine all concepts', 'Professional project structure', 'CLI interface', 'Data persistence', 'Unit tests'],
    explanationId: '### Structure\nmodels/, services/, cli/, tests/.\n\n### OOP\nTask class dengan methods.\n\n### Testing\npytest dengan fixtures.',
    explanationEn: '### Structure\nOrganized directories.\n\n### OOP\nTask class.\n\n### Testing\npytest.',
    experimentsId: ['Export CSV', 'Due reminders', 'Statistics', 'Plugins'],
    experimentsEn: ['Export CSV', 'Due reminders', 'Statistics', 'Plugins'],
    challengeId: 'Buat Task Manager Pro lengkap: OOP, CLI, tests.',
    challengeEn: 'Build complete Task Manager Pro: OOP, CLI, tests.',
    summaryId: 'Minggu 12 dari 12: **Capstone** (Level: Lanjutan). Selesai!',
    summaryEn: 'Week 12 of 12: **Capstone** (Level: Advanced). Complete!' }
];

for (const level of LEVELS) {
  level.weeks = MODULES.filter(m => m.level === level.levelId).map(m => ({
    week: m.week, topicId: m.topicId, titleId: m.titleId, titleEn: m.titleEn,
  }));
}

gen.writeFiles(MODULES, LEVELS);
