import type { LevelInfo } from '../curriculum';

// Angular curriculum — research-backed structure
// Generated by generate-angular-materials.mjs
export const angularCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar Angular: components, templates, directives, services.',
    descEn: 'Angular basics: components, templates, directives, services.',
    weeks: [
      { week: 1, topicId: 'components-templates', titleId: 'Components & Templates', titleEn: 'Components & Templates' },
      { week: 2, topicId: 'directives-pipes', titleId: 'Directives & Pipes', titleEn: 'Directives & Pipes' },
      { week: 3, topicId: 'services-di', titleId: 'Services & Dependency Injection', titleEn: 'Services & Dependency Injection' },
      { week: 4, topicId: 'component-communication', titleId: 'Component Communication', titleEn: 'Component Communication' },
      { week: 5, topicId: 'template-forms', titleId: 'Template-driven Forms', titleEn: 'Template-driven Forms' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Angular menengah: routing, forms, HTTP, RxJS.',
    descEn: 'Intermediate Angular: routing, forms, HTTP, RxJS.',
    weeks: [
      { week: 6, topicId: 'routing', titleId: 'Angular Router', titleEn: 'Angular Router' },
      { week: 7, topicId: 'reactive-forms', titleId: 'Reactive Forms', titleEn: 'Reactive Forms' },
      { week: 8, topicId: 'http-client', titleId: 'HTTP Client & APIs', titleEn: 'HTTP Client & APIs' },
      { week: 9, topicId: 'rxjs', titleId: 'RxJS Fundamentals', titleEn: 'RxJS Fundamentals' },
      { week: 10, topicId: 'state-management', titleId: 'State Management', titleEn: 'State Management' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Angular lanjutan: state, testing, performance, proyek.',
    descEn: 'Advanced Angular: state, testing, performance, project.',
    weeks: [
      { week: 11, topicId: 'testing-angular', titleId: 'Testing Angular', titleEn: 'Testing Angular' },
      { week: 12, topicId: 'performance', titleId: 'Performance Optimization', titleEn: 'Performance Optimization' },
      { week: 13, topicId: 'advanced-patterns', titleId: 'Advanced Patterns', titleEn: 'Advanced Patterns' },
      { week: 14, topicId: 'capstone', titleId: 'Capstone: Enterprise App', titleEn: 'Capstone: Enterprise App' }
    ],
  }
];
