import type { LevelInfo } from '../curriculum';

// CodeIgniter 4 curriculum — research-backed structure
// Generated by generate-codeigniter4-materials.mjs
export const codeigniter4Curriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Fundamental CodeIgniter 4: setup, MVC, controllers, views, models, database.',
    descEn: 'CodeIgniter 4 fundamentals: setup, MVC, controllers, views, models, database.',
    weeks: [
      { week: 1, topicId: 'setup-ci4', titleId: 'Setup & Instalasi CI4', titleEn: 'Setup & CI4 Installation' },
      { week: 2, topicId: 'controllers-routing', titleId: 'Controllers & Routing', titleEn: 'Controllers & Routing' },
      { week: 3, topicId: 'views-templates', titleId: 'Views & Templates', titleEn: 'Views & Templates' },
      { week: 4, topicId: 'models-database', titleId: 'Models & Database', titleEn: 'Models & Database' },
      { week: 5, topicId: 'migrations-seeds', titleId: 'Migrations & Seeds', titleEn: 'Migrations & Seeds' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'CI4 menengah: validation, authentication, REST API, testing, proyek akhir.',
    descEn: 'Intermediate CI4: validation, authentication, REST API, testing, final project.',
    weeks: [
      { week: 6, topicId: 'validation', titleId: 'Validation & Form Handling', titleEn: 'Validation & Form Handling' },
      { week: 7, topicId: 'authentication', titleId: 'Authentication & Authorization', titleEn: 'Authentication & Authorization' },
      { week: 8, topicId: 'rest-api', titleId: 'REST API Development', titleEn: 'REST API Development' },
      { week: 9, topicId: 'testing', titleId: 'Testing dengan PHPUnit', titleEn: 'Testing with PHPUnit' },
      { week: 10, topicId: 'capstone-project', titleId: 'Capstone: Task Management API', titleEn: 'Capstone: Task Management API' }
    ],
  }
];
