import type { LevelInfo } from '../curriculum';

// C# curriculum — research-backed structure
// Generated by generate-csharp-materials.mjs
export const csharpCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Fundamental C#: sintaks, tipe data, OOP, control flow — urutan resmi Microsoft Learn.',
    descEn: 'C# fundamentals: syntax, types, OOP, control flow — official Microsoft Learn order.',
    weeks: [
      { week: 1, topicId: 'setup-dan-sintaks', titleId: 'Setup, Toolchain & Sintaks Dasar', titleEn: 'Setup, Toolchain & Basic Syntax' },
      { week: 2, topicId: 'tipe-data-variabel', titleId: 'Tipe Data & Variabel', titleEn: 'Data Types & Variables' },
      { week: 3, topicId: 'control-flow', titleId: 'Control Flow', titleEn: 'Control Flow' },
      { week: 4, topicId: 'oop-class-object', titleId: 'OOP: Class & Object', titleEn: 'OOP: Classes & Objects' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Idiomatic C#: LINQ, async/await, generics, error handling — C# in Depth pathway.',
    descEn: 'Idiomatic C#: LINQ, async/await, generics, error handling — C# in Depth pathway.',
    weeks: [
      { week: 5, topicId: 'linq', titleId: 'LINQ', titleEn: 'LINQ' },
      { week: 6, topicId: 'async-await', titleId: 'Async/Await', titleEn: 'Async/Await' },
      { week: 7, topicId: 'generics', titleId: 'Generics', titleEn: 'Generics' },
      { week: 8, topicId: 'error-handling', titleId: 'Error Handling', titleEn: 'Error Handling' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Production C#: design patterns, testing, Web API, capstone project.',
    descEn: 'Production C#: design patterns, testing, Web API, capstone project.',
    weeks: [
      { week: 9, topicId: 'design-patterns', titleId: 'Design Patterns', titleEn: 'Design Patterns' },
      { week: 10, topicId: 'testing', titleId: 'Testing', titleEn: 'Testing' },
      { week: 11, topicId: 'web-api', titleId: 'Web API', titleEn: 'Web API' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: Full Stack App', titleEn: 'Capstone: Full Stack App' }
    ],
  }
];
