import type { LevelInfo } from '../curriculum';

// CSS3 curriculum — research-backed structure
// Generated by generate-css3-materials.mjs
export const css3Curriculum: LevelInfo[] = [
  {
    levelId: 'css',
    nameId: 'CSS3 Lengkap',
    nameEn: 'Complete CSS3',
    descId: 'Dari nol hingga mahir: selector, layout, animasi, responsive, dan arsitektur CSS modern.',
    descEn: 'From zero to expert: selectors, layouts, animations, responsive design, and modern CSS architecture.',
    weeks: [
      { week: 1, topicId: 'selector-dasar', titleId: 'Selector & Basic Styling', titleEn: 'Selectors & Basic Styling' },
      { week: 2, topicId: 'box-model', titleId: 'Box Model', titleEn: 'Box Model' },
      { week: 3, topicId: 'warna-teks-tipografi', titleId: 'Warna, Teks & Tipografi', titleEn: 'Colors, Text & Typography' },
      { week: 4, topicId: 'flexbox', titleId: 'Flexbox', titleEn: 'Flexbox' },
      { week: 5, topicId: 'css-grid', titleId: 'CSS Grid', titleEn: 'CSS Grid' },
      { week: 6, topicId: 'positioning', titleId: 'Positioning', titleEn: 'Positioning' },
      { week: 7, topicId: 'responsive-design', titleId: 'Responsive Design', titleEn: 'Responsive Design' },
      { week: 8, topicId: 'animasi-transisi', titleId: 'Animasi & Transisi', titleEn: 'Animations & Transitions' },
      { week: 9, topicId: 'css-variables', titleId: 'CSS Variables', titleEn: 'CSS Variables' },
      { week: 10, topicId: 'arsitektur-css', titleId: 'Arsitektur CSS', titleEn: 'CSS Architecture' },
      { week: 11, topicId: 'modern-css', titleId: 'Modern CSS', titleEn: 'Modern CSS' },
      { week: 12, topicId: 'proyek-akhir', titleId: 'Proyek Akhir: Landing Page', titleEn: 'Final Project: Landing Page' }
    ],
  }
];
