import type { LevelInfo } from '../curriculum';

// Django curriculum — research-backed structure
// Generated by generate-django-materials.mjs
export const djangoCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Fundamental Django: setup, models, views, templates.',
    descEn: 'Django fundamentals: setup, models, views, templates.',
    weeks: [
      { week: 1, topicId: 'setup-django', titleId: 'Setup & Instalasi Django', titleEn: 'Setup & Django Installation' },
      { week: 2, topicId: 'models-orm', titleId: 'Models & ORM', titleEn: 'Models & ORM' },
      { week: 3, topicId: 'views-urls', titleId: 'Views & URL Routing', titleEn: 'Views & URL Routing' },
      { week: 4, topicId: 'templates', titleId: 'Templates & Template Language', titleEn: 'Templates & Template Language' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Django menengah: forms, auth, admin, REST.',
    descEn: 'Intermediate Django: forms, auth, admin, REST.',
    weeks: [
      { week: 5, topicId: 'forms-validation', titleId: 'Forms & Validation', titleEn: 'Forms & Validation' },
      { week: 6, topicId: 'authentication', titleId: 'Authentication & Authorization', titleEn: 'Authentication & Authorization' },
      { week: 7, topicId: 'admin-panel', titleId: 'Admin Panel', titleEn: 'Admin Panel' },
      { week: 8, topicId: 'rest-api', titleId: 'REST API dengan DRF', titleEn: 'REST API with DRF' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Django lanjutan: testing, caching, deployment.',
    descEn: 'Advanced Django: testing, caching, deployment.',
    weeks: [
      { week: 9, topicId: 'testing', titleId: 'Testing dengan pytest', titleEn: 'Testing with pytest' },
      { week: 10, topicId: 'caching', titleId: 'Caching & Performance', titleEn: 'Caching & Performance' },
      { week: 11, topicId: 'deployment', titleId: 'Deployment & DevOps', titleEn: 'Deployment & DevOps' },
      { week: 12, topicId: 'capstone-project', titleId: 'Capstone: E-Commerce Platform', titleEn: 'Capstone: E-Commerce Platform' }
    ],
  }
];
