import type { LevelInfo } from '../curriculum';

// Docker curriculum — research-backed structure
// Generated by generate-docker-materials.mjs
export const dockerCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Fundamental Docker: konsep, image, container, Dockerfile — urutan resmi Docker Docs.',
    descEn: 'Docker fundamentals: concepts, images, containers, Dockerfile — official Docker Docs order.',
    weeks: [
      { week: 1, topicId: 'konsep-docker', titleId: 'Konsep Docker', titleEn: 'Docker Concepts' },
      { week: 2, topicId: 'image-registry', titleId: 'Image & Registry', titleEn: 'Images & Registries' },
      { week: 3, topicId: 'container-management', titleId: 'Container Management', titleEn: 'Container Management' },
      { week: 4, topicId: 'dockerfile', titleId: 'Dockerfile', titleEn: 'Dockerfile' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Docker workflows: volume, network, compose, multi-stage build — Docker Deep Dive pathway.',
    descEn: 'Docker workflows: volumes, networking, compose, multi-stage builds — Docker Deep Dive pathway.',
    weeks: [
      { week: 5, topicId: 'volume-data', titleId: 'Volume & Data Persistence', titleEn: 'Volumes & Data Persistence' },
      { week: 6, topicId: 'networking', titleId: 'Networking', titleEn: 'Networking' },
      { week: 7, topicId: 'docker-compose', titleId: 'Docker Compose', titleEn: 'Docker Compose' },
      { week: 8, topicId: 'multi-stage-build', titleId: 'Multi-Stage Build', titleEn: 'Multi-Stage Builds' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Docker production: security, CI/CD, orchestration, Kubernetes, capstone project.',
    descEn: 'Production Docker: security, CI/CD, orchestration, Kubernetes, capstone project.',
    weeks: [
      { week: 9, topicId: 'security', titleId: 'Security', titleEn: 'Security' },
      { week: 10, topicId: 'cicd', titleId: 'CI/CD Pipeline', titleEn: 'CI/CD Pipelines' },
      { week: 11, topicId: 'orchestration', titleId: 'Orchestration', titleEn: 'Orchestration' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: Production Pipeline', titleEn: 'Capstone: Production Pipeline' }
    ],
  }
];
