import type { LevelInfo } from '../curriculum';

// Go curriculum — research-backed structure
// Generated by generate-golang-materials.mjs
export const golangCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dari nol: toolchain, sintaks, tipe data, fungsi, koleksi, struct — urutan resmi Go Tour.',
    descEn: 'From scratch: toolchain, syntax, types, functions, collections, structs — official Go Tour order.',
    weeks: [
      { week: 1, topicId: 'setup-dan-sintaks', titleId: 'Setup, Toolchain & Sintaks Dasar', titleEn: 'Setup, Toolchain & Basic Syntax' },
      { week: 2, topicId: 'variabel-tipe-kontrol', titleId: 'Variabel, Tipe & Control Flow', titleEn: 'Variables, Types & Control Flow' },
      { week: 3, topicId: 'fungsi-error', titleId: 'Fungsi & Error Handling', titleEn: 'Functions & Error Handling' },
      { week: 4, topicId: 'koleksi-slice-map', titleId: 'Koleksi: Slice, Map & String', titleEn: 'Collections: Slices, Maps & Strings' },
      { week: 5, topicId: 'struct-method', titleId: 'Struct & Method', titleEn: 'Structs & Methods' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Idiomatic Go: interface, pointer, package, concurrency, context — LevelUpGo pathway.',
    descEn: 'Idiomatic Go: interfaces, pointers, packages, concurrency, context — LevelUpGo pathway.',
    weeks: [
      { week: 6, topicId: 'interface-generics', titleId: 'Interface & Generics', titleEn: 'Interfaces & Generics' },
      { week: 7, topicId: 'pointer-package', titleId: 'Pointer, Memory & Package', titleEn: 'Pointers, Memory & Packages' },
      { week: 8, topicId: 'goroutine-channel', titleId: 'Goroutine & Channel', titleEn: 'Goroutines & Channels' },
      { week: 9, topicId: 'context-sync', titleId: 'Context & Sinkronisasi', titleEn: 'Context & Synchronization' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Production Go: stdlib, encoding, HTTP server, testing, capstone project.',
    descEn: 'Production Go: stdlib, encoding, HTTP server, testing, capstone project.',
    weeks: [
      { week: 10, topicId: 'stdlib-io-encoding', titleId: 'Stdlib: I/O, Time & Encoding', titleEn: 'Stdlib: I/O, Time & Encoding' },
      { week: 11, topicId: 'http-server', titleId: 'HTTP Server & Middleware', titleEn: 'HTTP Server & Middleware' },
      { week: 12, topicId: 'testing-cli', titleId: 'Testing & CLI Tools', titleEn: 'Testing & CLI Tools' },
      { week: 13, topicId: 'capstone', titleId: 'Capstone: REST API + CLI', titleEn: 'Capstone: REST API + CLI' }
    ],
  }
];
