import type { LevelInfo } from '../curriculum';

// GraphQL curriculum — research-backed structure
// Generated by generate-graphql-materials.mjs
export const graphqlCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar GraphQL: schema, query, mutation, resolver, tipe.',
    descEn: 'GraphQL fundamentals: schema, queries, mutations, resolvers, types.',
    weeks: [
      { week: 1, topicId: 'schema-types', titleId: 'Schema & Tipe Dasar', titleEn: 'Schema & Basic Types' },
      { week: 2, topicId: 'queries', titleId: 'Queries', titleEn: 'Queries' },
      { week: 3, topicId: 'mutations', titleId: 'Mutations', titleEn: 'Mutations' },
      { week: 4, topicId: 'resolvers', titleId: 'Resolvers', titleEn: 'Resolvers' },
      { week: 5, topicId: 'apollo-server', titleId: 'Apollo Server & Client', titleEn: 'Apollo Server & Client' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'GraphQL lanjutan: auth, dataloader, subscription, testing.',
    descEn: 'Advanced GraphQL: auth, dataloader, subscriptions, testing.',
    weeks: [
      { week: 6, topicId: 'authentication', titleId: 'Authentication & Authorization', titleEn: 'Authentication & Authorization' },
      { week: 7, topicId: 'dataloader', titleId: 'DataLoader & N+1 Problem', titleEn: 'DataLoader & N+1 Problem' },
      { week: 8, topicId: 'subscriptions', titleId: 'Subscriptions', titleEn: 'Subscriptions' },
      { week: 9, topicId: 'testing', titleId: 'Testing & Error Handling', titleEn: 'Testing & Error Handling' },
      { week: 10, topicId: 'capstone-project', titleId: 'Capstone: E-Commerce GraphQL', titleEn: 'Capstone: E-Commerce GraphQL' }
    ],
  }
];
