import type { LevelInfo } from '../curriculum';

// HTML5 curriculum — research-backed structure
// Generated by generate-html5-materials.mjs
export const html5Curriculum: LevelInfo[] = [
  {
    levelId: 'html',
    nameId: 'HTML5 Lengkap',
    nameEn: 'Complete HTML5',
    descId: 'Dari nol hingga mahir: struktur, elemen, form, semantic, aksesibilitas, dan SEO.',
    descEn: 'From zero to expert: structure, elements, forms, semantics, accessibility, and SEO.',
    weeks: [
      { week: 1, topicId: 'pengantar-html', titleId: 'Pengantar HTML', titleEn: 'Introduction to HTML' },
      { week: 2, topicId: 'format-teks-tipografi', titleId: 'Format Teks & Tipografi', titleEn: 'Text Formatting & Typography' },
      { week: 3, topicId: 'link-navigasi', titleId: 'Link & Navigasi', titleEn: 'Links & Navigation' },
      { week: 4, topicId: 'gambar-media', titleId: 'Gambar & Media', titleEn: 'Images & Media' },
      { week: 5, topicId: 'list-daftar', titleId: 'List & Daftar', titleEn: 'Lists' },
      { week: 6, topicId: 'tabel', titleId: 'Tabel', titleEn: 'Tables' },
      { week: 7, topicId: 'form-input', titleId: 'Form & Input', titleEn: 'Forms & Inputs' },
      { week: 8, topicId: 'validasi-form', titleId: 'Validasi Form', titleEn: 'Form Validation' },
      { week: 9, topicId: 'semantic-html', titleId: 'Semantic HTML', titleEn: 'Semantic HTML' },
      { week: 10, topicId: 'multimedia-audio-video', titleId: 'Multimedia: Audio & Video', titleEn: 'Multimedia: Audio & Video' },
      { week: 11, topicId: 'html-apis', titleId: 'HTML APIs', titleEn: 'HTML APIs' },
      { week: 12, topicId: 'aksesibilitas', titleId: 'Aksesibilitas (a11y)', titleEn: 'Accessibility (a11y)' },
      { week: 13, topicId: 'seo-meta-tags', titleId: 'SEO & Meta Tags', titleEn: 'SEO & Meta Tags' },
      { week: 14, topicId: 'proyek-akhir', titleId: 'Proyek Akhir: Website Portfolio', titleEn: 'Final Project: Portfolio Website' }
    ],
  }
];
