import type { LevelInfo } from '../curriculum';

// JavaScript curriculum — research-backed structure
// Generated by generate-javascript-materials.mjs
export const javascriptCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dari nol: sintaks, tipe data, fungsi, dan manipulasi DOM.',
    descEn: 'From scratch: syntax, data types, functions, and DOM manipulation.',
    weeks: [
      { week: 1, topicId: 'dasar-sintaks', titleId: 'Dasar Sintaks JavaScript', titleEn: 'JavaScript Syntax Basics' },
      { week: 2, topicId: 'tipe-data-struktur', titleId: 'Tipe Data & Struktur Data', titleEn: 'Data Types & Data Structures' },
      { week: 3, topicId: 'control-flow', titleId: 'Control Flow', titleEn: 'Control Flow' },
      { week: 4, topicId: 'fungsi', titleId: 'Fungsi', titleEn: 'Functions' },
      { week: 5, topicId: 'dom-manipulation', titleId: 'DOM Manipulation', titleEn: 'DOM Manipulation' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'JavaScript modern: async, ES6+, modules, dan error handling.',
    descEn: 'Modern JavaScript: async, ES6+, modules, and error handling.',
    weeks: [
      { week: 6, topicId: 'events-handling', titleId: 'Events & Event Handling', titleEn: 'Events & Event Handling' },
      { week: 7, topicId: 'async-javascript', titleId: 'Async JavaScript', titleEn: 'Async JavaScript' },
      { week: 8, topicId: 'es6-features', titleId: 'ES6+ Features', titleEn: 'ES6+ Features' },
      { week: 9, topicId: 'modules', titleId: 'Modules', titleEn: 'Modules' },
      { week: 10, topicId: 'error-handling', titleId: 'Error Handling', titleEn: 'Error Handling' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Production JS: design patterns, testing, performa, dan proyek capstone.',
    descEn: 'Production JS: design patterns, testing, performance, and capstone project.',
    weeks: [
      { week: 11, topicId: 'design-patterns', titleId: 'Design Patterns', titleEn: 'Design Patterns' },
      { week: 12, topicId: 'testing', titleId: 'Testing JavaScript', titleEn: 'Testing JavaScript' },
      { week: 13, topicId: 'performance', titleId: 'Performance Optimization', titleEn: 'Performance Optimization' },
      { week: 14, topicId: 'capstone', titleId: 'Capstone: Task Manager App', titleEn: 'Capstone: Task Manager App' }
    ],
  }
];
