import type { LevelInfo } from '../curriculum';

// Laravel curriculum — research-backed structure
// Generated by generate-laravel-materials.mjs
export const laravelCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Fundamental Laravel: setup, routing, Blade template, dan Eloquent ORM.',
    descEn: 'Laravel fundamentals: setup, routing, Blade templates, and Eloquent ORM.',
    weeks: [
      { week: 1, topicId: 'setup-laravel', titleId: 'Setup & Instalasi Laravel', titleEn: 'Setup & Laravel Installation' },
      { week: 2, topicId: 'routing-controllers', titleId: 'Routing & Controllers', titleEn: 'Routing & Controllers' },
      { week: 3, topicId: 'blade-templates', titleId: 'Blade Templates', titleEn: 'Blade Templates' },
      { week: 4, topicId: 'eloquent-orm', titleId: 'Eloquent ORM', titleEn: 'Eloquent ORM' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Laravel menengah: authentication, relasi database, validasi, dan file storage.',
    descEn: 'Intermediate Laravel: authentication, database relationships, validation, and file storage.',
    weeks: [
      { week: 5, topicId: 'authentication', titleId: 'Authentication & Authorization', titleEn: 'Authentication & Authorization' },
      { week: 6, topicId: 'relationships', titleId: 'Database Relationships', titleEn: 'Database Relationships' },
      { week: 7, topicId: 'validation', titleId: 'Validation & Form Requests', titleEn: 'Validation & Form Requests' },
      { week: 8, topicId: 'file-storage', titleId: 'File Storage & Upload', titleEn: 'File Storage & Upload' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Laravel lanjutan: testing, queues, REST API, dan capstone project.',
    descEn: 'Advanced Laravel: testing, queues, REST API, and capstone project.',
    weeks: [
      { week: 9, topicId: 'testing', titleId: 'Testing dengan PHPUnit', titleEn: 'Testing with PHPUnit' },
      { week: 10, topicId: 'queues-jobs', titleId: 'Queues & Background Jobs', titleEn: 'Queues & Background Jobs' },
      { week: 11, topicId: 'rest-api', titleId: 'REST API Development', titleEn: 'REST API Development' },
      { week: 12, topicId: 'capstone-project', titleId: 'Capstone: E-Commerce API', titleEn: 'Capstone: E-Commerce API' }
    ],
  }
];
