import type { LevelInfo } from '../curriculum';

// MongoDB curriculum — research-backed structure
// Generated by generate-mongodb-materials.mjs
export const mongodbCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar MongoDB: dokumen, CRUD, index, aggregation.',
    descEn: 'MongoDB fundamentals: documents, CRUD, indexes, aggregation.',
    weeks: [
      { week: 1, topicId: 'dokumen-crud', titleId: 'Dokumen & CRUD Dasar', titleEn: 'Documents & Basic CRUD' },
      { week: 2, topicId: 'update-delete', titleId: 'Update & Delete Dokumen', titleEn: 'Update & Delete Documents' },
      { week: 3, topicId: 'index', titleId: 'Index & Performa', titleEn: 'Indexes & Performance' },
      { week: 4, topicId: 'aggregation-basics', titleId: 'Aggregation Basics', titleEn: 'Aggregation Basics' },
      { week: 5, topicId: 'schema-design', titleId: 'Schema Design Patterns', titleEn: 'Schema Design Patterns' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'MongoDB lanjutan: aggregation lanjut, schema design, replikasi, performa.',
    descEn: 'Advanced MongoDB: advanced aggregation, schema design, replication, performance.',
    weeks: [
      { week: 6, topicId: 'aggregation-advanced', titleId: 'Aggregation Lanjutan', titleEn: 'Advanced Aggregation' },
      { week: 7, topicId: 'replikasi', titleId: 'Replica Set & Sharding', titleEn: 'Replica Sets & Sharding' },
      { week: 8, topicId: 'performa-tuning', titleId: 'Performa & Tuning', titleEn: 'Performance & Tuning' },
      { week: 9, topicId: 'change-streams', titleId: 'Change Streams & Transactions', titleEn: 'Change Streams & Transactions' },
      { week: 10, topicId: 'capstone-project', titleId: 'Capstone: E-Commerce MongoDB', titleEn: 'Capstone: E-Commerce MongoDB' }
    ],
  }
];
