import type { LevelInfo } from '../curriculum';

// MySQL curriculum — research-backed structure
// Generated by generate-mysql-materials.mjs
export const mysqlCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar MySQL: tabel, query, join, index, stored procedure.',
    descEn: 'MySQL fundamentals: tables, queries, joins, indexes, stored procedures.',
    weeks: [
      { week: 1, topicId: 'dasar-mysql', titleId: 'Dasar MySQL & Tabel', titleEn: 'MySQL Basics & Tables' },
      { week: 2, topicId: 'crud-query', titleId: 'CRUD & Query Lanjutan', titleEn: 'CRUD & Advanced Queries' },
      { week: 3, topicId: 'join-relasi', titleId: 'JOIN & Relasi Tabel', titleEn: 'JOINs & Table Relations' },
      { week: 4, topicId: 'index-optimasi', titleId: 'Index & Optimasi Query', titleEn: 'Indexes & Query Optimization' },
      { week: 5, topicId: 'stored-procedure', titleId: 'Stored Procedure & Function', titleEn: 'Stored Procedures & Functions' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'MySQL lanjutan: transaksi, performa, replikasi, keamanan, proyek.',
    descEn: 'Advanced MySQL: transactions, performance, replication, security, project.',
    weeks: [
      { week: 6, topicId: 'transaksi-acid', titleId: 'Transaksi & ACID', titleEn: 'Transactions & ACID' },
      { week: 7, topicId: 'performa-tuning', titleId: 'Performa & Tuning', titleEn: 'Performance & Tuning' },
      { week: 8, topicId: 'replikasi', titleId: 'Replikasi & High Availability', titleEn: 'Replication & High Availability' },
      { week: 9, topicId: 'keamanan', titleId: 'Keamanan & User Management', titleEn: 'Security & User Management' },
      { week: 10, topicId: 'capstone-project', titleId: 'Capstone: E-Commerce Database', titleEn: 'Capstone: E-Commerce Database' }
    ],
  }
];
