import type { LevelInfo } from '../curriculum';

// NestJS curriculum — research-backed structure
// Generated by generate-nestjs-materials.mjs
export const nestjsCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar NestJS: Controllers, Providers, Modules, DI.',
    descEn: 'NestJS basics: Controllers, Providers, Modules, DI.',
    weeks: [
      { week: 1, topicId: 'controllers-routing', titleId: 'Controllers & Routing', titleEn: 'Controllers & Routing' },
      { week: 2, topicId: 'providers-services', titleId: 'Providers & Services', titleEn: 'Providers & Services' },
      { week: 3, topicId: 'modules-di', titleId: 'Modules & Dependency Injection', titleEn: 'Modules & Dependency Injection' },
      { week: 4, topicId: 'database-typeorm', titleId: 'Database & TypeORM', titleEn: 'Database & TypeORM' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Fitur lanjut: Pipes, Guards, ORM, Auth.',
    descEn: 'Advanced features: Pipes, Guards, ORM, Auth.',
    weeks: [
      { week: 5, topicId: 'pipes-validation', titleId: 'Pipes & Validation', titleEn: 'Pipes & Validation' },
      { week: 6, topicId: 'guards-auth', titleId: 'Guards & Authentication', titleEn: 'Guards & Authentication' },
      { week: 7, topicId: 'orm-advanced', titleId: 'ORM Advanced & Relations', titleEn: 'ORM Advanced & Relations' },
      { week: 8, topicId: 'error-logging', titleId: 'Error Handling & Logging', titleEn: 'Error Handling & Logging' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Production: Testing, WebSockets, Microservices, Project.',
    descEn: 'Production: Testing, WebSockets, Microservices, Project.',
    weeks: [
      { week: 9, topicId: 'testing', titleId: 'Testing NestJS', titleEn: 'Testing NestJS' },
      { week: 10, topicId: 'websockets', titleId: 'WebSockets & Real-time', titleEn: 'WebSockets & Real-time' },
      { week: 11, topicId: 'microservices', titleId: 'Microservices', titleEn: 'Microservices' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: Enterprise API', titleEn: 'Capstone: Enterprise API' }
    ],
  }
];
