import type { LevelInfo } from '../curriculum';

// Next.js curriculum — research-backed structure
// Generated by generate-nextjs-materials.mjs
export const nextjsCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar Next.js: setup, routing, layouts, komponen — membangun web app modern.',
    descEn: 'Next.js basics: setup, routing, layouts, components — building modern web apps.',
    weeks: [
      { week: 1, topicId: 'setup-dasar', titleId: 'Setup & Konsep Dasar', titleEn: 'Setup & Core Concepts' },
      { week: 2, topicId: 'routing-navigation', titleId: 'Routing & Navigation', titleEn: 'Routing & Navigation' },
      { week: 3, topicId: 'server-client', titleId: 'Server & Client Components', titleEn: 'Server & Client Components' },
      { week: 4, topicId: 'styling-optimization', titleId: 'Styling & Optimasi', titleEn: 'Styling & Optimization' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Next.js tingkat menengah: data fetching, server actions, forms — aplikasi dinamis.',
    descEn: 'Intermediate Next.js: data fetching, server actions, forms — dynamic applications.',
    weeks: [
      { week: 5, topicId: 'data-fetching', titleId: 'Data Fetching', titleEn: 'Data Fetching' },
      { week: 6, topicId: 'server-actions', titleId: 'Server Actions & Mutations', titleEn: 'Server Actions & Mutations' },
      { week: 7, topicId: 'loading-error', titleId: 'Loading & Error UI', titleEn: 'Loading & Error UI' },
      { week: 8, topicId: 'middleware-auth', titleId: 'Middleware & Auth Dasar', titleEn: 'Middleware & Basic Auth' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Next.js tingkat lanjutan: auth, database, deployment, proyek capstone.',
    descEn: 'Advanced Next.js: auth, database, deployment, capstone project.',
    weeks: [
      { week: 9, topicId: 'database-orm', titleId: 'Database & ORM', titleEn: 'Database & ORM' },
      { week: 10, topicId: 'advanced-auth', titleId: 'Advanced Auth & Security', titleEn: 'Advanced Auth & Security' },
      { week: 11, topicId: 'deployment-production', titleId: 'Deployment & Production', titleEn: 'Deployment & Production' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: SaaS App', titleEn: 'Capstone: SaaS App' }
    ],
  }
];
