import type { LevelInfo } from '../curriculum';

// Node.js curriculum — research-backed structure
// Generated by generate-nodejs-materials.mjs
export const nodejsCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar Node.js: runtime, modules, file system, events.',
    descEn: 'Node.js basics: runtime, modules, file system, events.',
    weeks: [
      { week: 1, topicId: 'dasar-nodejs', titleId: 'Dasar Node.js & Runtime', titleEn: 'Node.js Basics & Runtime' },
      { week: 2, topicId: 'modules-npm', titleId: 'Modules & NPM', titleEn: 'Modules & NPM' },
      { week: 3, topicId: 'file-system', titleId: 'File System & Path', titleEn: 'File System & Path' },
      { week: 4, topicId: 'events-async', titleId: 'Events & Async Programming', titleEn: 'Events & Async Programming' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Backend: Express, REST API, auth, database.',
    descEn: 'Backend: Express, REST API, auth, database.',
    weeks: [
      { week: 5, topicId: 'express-server', titleId: 'Express.js & Web Server', titleEn: 'Express.js & Web Server' },
      { week: 6, topicId: 'rest-api', titleId: 'REST API Design', titleEn: 'REST API Design' },
      { week: 7, topicId: 'auth', titleId: 'Authentication & Authorization', titleEn: 'Authentication & Authorization' },
      { week: 8, topicId: 'database', titleId: 'Database & ORM', titleEn: 'Database & ORM' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Production: testing, performance, deployment, capstone.',
    descEn: 'Production: testing, performance, deployment, capstone.',
    weeks: [
      { week: 9, topicId: 'testing', titleId: 'Testing & Quality', titleEn: 'Testing & Quality' },
      { week: 10, topicId: 'performance', titleId: 'Performance & Security', titleEn: 'Performance & Security' },
      { week: 11, topicId: 'deployment', titleId: 'Deployment & DevOps', titleEn: 'Deployment & DevOps' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: Full-Stack API', titleEn: 'Capstone: Full-Stack API' }
    ],
  }
];
