import type { LevelInfo } from '../curriculum';

// PHP curriculum — research-backed structure
// Generated by generate-php-materials.mjs
export const phpCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar PHP: sintaks, tipe data, fungsi, array, OOP, dan penanganan form.',
    descEn: 'PHP fundamentals: syntax, types, functions, arrays, OOP, and form handling.',
    weeks: [
      { week: 1, topicId: 'sintaks-dasar', titleId: 'Sintaks Dasar & Variabel', titleEn: 'Basic Syntax & Variables' },
      { week: 2, topicId: 'operator-kontrol', titleId: 'Operator & Control Flow', titleEn: 'Operators & Control Flow' },
      { week: 3, topicId: 'fungsi-scope', titleId: 'Fungsi & Lingkup Variabel', titleEn: 'Functions & Variable Scope' },
      { week: 4, topicId: 'array-manipulasi', titleId: 'Array & Manipulasi', titleEn: 'Arrays & Manipulation' },
      { week: 5, topicId: 'oop-dasar', titleId: 'Object-Oriented Programming', titleEn: 'Object-Oriented Programming' },
      { week: 6, topicId: 'form-handling', titleId: 'Form Handling & Validasi', titleEn: 'Form Handling & Validation' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'PHP produksi: keamanan, PDO, Composer, testing, design pattern, proyek akhir.',
    descEn: 'Production PHP: security, PDO, Composer, testing, design patterns, final project.',
    weeks: [
      { week: 7, topicId: 'keamanan-php', titleId: 'Keamanan PHP', titleEn: 'PHP Security' },
      { week: 8, topicId: 'pdo-database', titleId: 'PDO & Database', titleEn: 'PDO & Database' },
      { week: 9, topicId: 'composer-autoloading', titleId: 'Composer & Autoloading', titleEn: 'Composer & Autoloading' },
      { week: 10, topicId: 'testing-phpunit', titleId: 'Testing dengan PHPUnit', titleEn: 'Testing with PHPUnit' },
      { week: 11, topicId: 'design-patterns', titleId: 'Design Patterns', titleEn: 'Design Patterns' },
      { week: 12, topicId: 'capstone-project', titleId: 'Capstone: Aplikasi Blog', titleEn: 'Capstone: Blog Application' }
    ],
  }
];
