import type { LevelInfo } from '../curriculum';

// PostgreSQL curriculum — research-backed structure
// Generated by generate-postgresql-materials.mjs
export const postgresqlCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar SQL dan PostgreSQL: tabel, query, join, index, fungsi.',
    descEn: 'SQL and PostgreSQL fundamentals.',
    weeks: [
      { week: 1, topicId: 'dasar-postgresql', titleId: 'Dasar PostgreSQL & Tabel', titleEn: 'PostgreSQL Basics & Tables' },
      { week: 2, topicId: 'crud-query', titleId: 'CRUD & Query Lanjutan', titleEn: 'CRUD & Advanced Queries' },
      { week: 3, topicId: 'join-relasi', titleId: 'JOIN & Relasi Tabel', titleEn: 'JOINs & Table Relations' },
      { week: 4, topicId: 'index-optimasi', titleId: 'Index & Optimasi Query', titleEn: 'Indexes & Query Optimization' },
      { week: 5, topicId: 'fungsi-trigger', titleId: 'Fungsi & Trigger', titleEn: 'Functions & Triggers' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'PostgreSQL lanjutan: window functions, JSONB, performa, replikasi, proyek.',
    descEn: 'Advanced PostgreSQL: window functions, JSONB, performance, replication, project.',
    weeks: [
      { week: 6, topicId: 'window-functions', titleId: 'Window Functions', titleEn: 'Window Functions' },
      { week: 7, topicId: 'jsonb-semi-struktural', titleId: 'JSONB & Semi-Structured Data', titleEn: 'JSONB & Semi-Structured Data' },
      { week: 8, topicId: 'performa-tuning', titleId: 'Performa & Tuning', titleEn: 'Performance & Tuning' },
      { week: 9, topicId: 'replikasi-ha', titleId: 'Replikasi & High Availability', titleEn: 'Replication & High Availability' },
      { week: 10, topicId: 'capstone-project', titleId: 'Capstone: E-Commerce Database', titleEn: 'Capstone: E-Commerce Database' }
    ],
  }
];
