import type { LevelInfo } from '../curriculum';

// Python curriculum — research-backed structure
// Generated by generate-python-materials.mjs
export const pythonCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar Python: syntax, tipe data, control flow, functions.',
    descEn: 'Python basics: syntax, data types, control flow, functions.',
    weeks: [
      { week: 1, topicId: 'dasar-python', titleId: 'Dasar Python & Sintaks', titleEn: 'Python Basics & Syntax' },
      { week: 2, topicId: 'tipe-data-operasi', titleId: 'Data Types & Operasi', titleEn: 'Data Types & Operations' },
      { week: 3, topicId: 'control-flow', titleId: 'Control Flow & Loops', titleEn: 'Control Flow & Loops' },
      { week: 4, topicId: 'functions', titleId: 'Functions & Modules', titleEn: 'Functions & Modules' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Python idiomatic: collections, OOP, file I/O, error handling.',
    descEn: 'Idiomatic Python: collections, OOP, file I/O, error handling.',
    weeks: [
      { week: 5, topicId: 'collections', titleId: 'Collections & Data Structures', titleEn: 'Collections & Data Structures' },
      { week: 6, topicId: 'oop', titleId: 'Object-Oriented Programming', titleEn: 'Object-Oriented Programming' },
      { week: 7, topicId: 'file-io', titleId: 'File I/O & Error Handling', titleEn: 'File I/O & Error Handling' },
      { week: 8, topicId: 'decorators-generators', titleId: 'Decorators & Generators', titleEn: 'Decorators & Generators' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Production Python: libraries, testing, CLI tools, capstone project.',
    descEn: 'Production Python: libraries, testing, CLI tools, capstone project.',
    weeks: [
      { week: 9, topicId: 'libraries', titleId: 'Libraries & Virtual Environments', titleEn: 'Libraries & Virtual Environments' },
      { week: 10, topicId: 'testing', titleId: 'Testing & Quality', titleEn: 'Testing & Quality' },
      { week: 11, topicId: 'cli', titleId: 'CLI & Automation', titleEn: 'CLI & Automation' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: Python Application', titleEn: 'Capstone: Python Application' }
    ],
  }
];
