import type { LevelInfo } from '../curriculum';

// Ruby on Rails curriculum — research-backed structure
// Generated by generate-rails-materials.mjs
export const railsCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Fundamental Rails: setup, MVC, migrations, views, dan scaffolding.',
    descEn: 'Rails fundamentals: setup, MVC, migrations, views, and scaffolding.',
    weeks: [
      { week: 1, topicId: 'setup-rails', titleId: 'Setup & Instalasi Rails', titleEn: 'Setup & Rails Installation' },
      { week: 2, topicId: 'mvc-architecture', titleId: 'MVC Architecture', titleEn: 'MVC Architecture' },
      { week: 3, topicId: 'migrations-database', titleId: 'Migrations & Database', titleEn: 'Migrations & Database' },
      { week: 4, topicId: 'views-erb', titleId: 'Views & ERB Templates', titleEn: 'Views & ERB Templates' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Rails menengah: authentication, associations, testing, dan API.',
    descEn: 'Intermediate Rails: authentication, associations, testing, and APIs.',
    weeks: [
      { week: 5, topicId: 'authentication', titleId: 'Authentication dengan Devise', titleEn: 'Authentication with Devise' },
      { week: 6, topicId: 'associations', titleId: 'Associations & Relationships', titleEn: 'Associations & Relationships' },
      { week: 7, topicId: 'testing', titleId: 'Testing dengan RSpec', titleEn: 'Testing with RSpec' },
      { week: 8, topicId: 'api-mode', titleId: 'Rails API Mode', titleEn: 'Rails API Mode' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Rails lanjutan: performance, background jobs, deployment, dan capstone.',
    descEn: 'Advanced Rails: performance, background jobs, deployment, and capstone.',
    weeks: [
      { week: 9, topicId: 'performance', titleId: 'Performance Optimization', titleEn: 'Performance Optimization' },
      { week: 10, topicId: 'background-jobs', titleId: 'Background Jobs & Sidekiq', titleEn: 'Background Jobs & Sidekiq' },
      { week: 11, topicId: 'deployment', titleId: 'Deployment & DevOps', titleEn: 'Deployment & DevOps' },
      { week: 12, topicId: 'capstone-project', titleId: 'Capstone: E-Commerce Platform', titleEn: 'Capstone: E-Commerce Platform' }
    ],
  }
];
