import type { LevelInfo } from '../curriculum';

// React curriculum — research-backed structure
// Generated by generate-react-materials.mjs
export const reactCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar React: JSX, komponen, props, state — fondasi membangun UI modern.',
    descEn: 'React basics: JSX, components, props, state — foundation for building modern UIs.',
    weeks: [
      { week: 1, topicId: 'jsx-dasar', titleId: 'JSX & Komponen Dasar', titleEn: 'JSX & Basic Components' },
      { week: 2, topicId: 'props-data-flow', titleId: 'Props & Data Flow', titleEn: 'Props & Data Flow' },
      { week: 3, topicId: 'state-usestate', titleId: 'State & useState', titleEn: 'State & useState' },
      { week: 4, topicId: 'useeffect-lifecycle', titleId: 'useEffect & Lifecycle', titleEn: 'useEffect & Lifecycle' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'React tingkat menengah: effects, router, context, forms — membangun aplikasi lengkap.',
    descEn: 'Intermediate React: effects, router, context, forms — building complete applications.',
    weeks: [
      { week: 5, topicId: 'react-router', titleId: 'React Router', titleEn: 'React Router' },
      { week: 6, topicId: 'context-api', titleId: 'Context API & useReducer', titleEn: 'Context API & useReducer' },
      { week: 7, topicId: 'forms-validation', titleId: 'Forms & Validasi', titleEn: 'Forms & Validation' },
      { week: 8, topicId: 'custom-hooks', titleId: 'Custom Hooks & Patterns', titleEn: 'Custom Hooks & Patterns' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'React tingkat lanjutan: patterns, testing, performance, proyek capstone.',
    descEn: 'Advanced React: patterns, testing, performance, capstone project.',
    weeks: [
      { week: 9, topicId: 'advanced-patterns', titleId: 'Advanced Patterns', titleEn: 'Advanced Patterns' },
      { week: 10, topicId: 'testing', titleId: 'Testing React', titleEn: 'Testing React' },
      { week: 11, topicId: 'performance', titleId: 'Performance Optimization', titleEn: 'Performance Optimization' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: E-Commerce App', titleEn: 'Capstone: E-Commerce App' }
    ],
  }
];
