import type { LevelInfo } from '../curriculum';

// Redis curriculum — research-backed structure
// Generated by generate-redis-materials.mjs
export const redisCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar Redis: tipe data, string, hash, list, set.',
    descEn: 'Redis fundamentals: data types, strings, hashes, lists, sets.',
    weeks: [
      { week: 1, topicId: 'tipe-data-string', titleId: 'Tipe Data & String', titleEn: 'Data Types & Strings' },
      { week: 2, topicId: 'hash', titleId: 'Hash', titleEn: 'Hashes' },
      { week: 3, topicId: 'list', titleId: 'List', titleEn: 'Lists' },
      { week: 4, topicId: 'set', titleId: 'Set', titleEn: 'Sets' },
      { week: 5, topicId: 'sorted-set', titleId: 'Sorted Set', titleEn: 'Sorted Sets' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Redis lanjutan: sorted sets, pub/sub, lua, clustering.',
    descEn: 'Advanced Redis: sorted sets, pub/sub, lua scripting, clustering.',
    weeks: [
      { week: 6, topicId: 'pub-sub', titleId: 'Pub/Sub & Streams', titleEn: 'Pub/Sub & Streams' },
      { week: 7, topicId: 'lua-scripting', titleId: 'Lua Scripting', titleEn: 'Lua Scripting' },
      { week: 8, topicId: 'clustering', titleId: 'Redis Cluster', titleEn: 'Redis Cluster' },
      { week: 9, topicId: 'caching-patterns', titleId: 'Caching Patterns', titleEn: 'Caching Patterns' },
      { week: 10, topicId: 'capstone-project', titleId: 'Capstone: Real-time Analytics', titleEn: 'Capstone: Real-time Analytics' }
    ],
  }
];
