import type { LevelInfo } from '../curriculum';

// Rust curriculum — research-backed structure
// Generated by generate-rust-materials.mjs
export const rustCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Fundamental Rust: sintaks, ownership, struct, enum, pattern matching — urutan resmi The Rust Book.',
    descEn: 'Rust fundamentals: syntax, ownership, structs, enums, pattern matching — official Rust Book order.',
    weeks: [
      { week: 1, topicId: 'setup-dan-sintaks', titleId: 'Setup, Toolchain & Sintaks Dasar', titleEn: 'Setup, Toolchain & Basic Syntax' },
      { week: 2, topicId: 'ownership-borrowing', titleId: 'Ownership & Borrowing', titleEn: 'Ownership & Borrowing' },
      { week: 3, topicId: 'struct-method', titleId: 'Struct & Method', titleEn: 'Structs & Methods' },
      { week: 4, topicId: 'enum-pattern-matching', titleId: 'Enum & Pattern Matching', titleEn: 'Enums & Pattern Matching' },
      { week: 5, topicId: 'collections-vec-hashmap', titleId: 'Collections: Vec, HashMap & String', titleEn: 'Collections: Vec, HashMap & String' },
      { week: 6, topicId: 'error-handling', titleId: 'Error Handling', titleEn: 'Error Handling' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Idiomatic Rust: trait, generics, lifetimes, testing, iterator — Rust by Example pathway.',
    descEn: 'Idiomatic Rust: traits, generics, lifetimes, testing, iterators — Rust by Example pathway.',
    weeks: [
      { week: 7, topicId: 'trait', titleId: 'Trait', titleEn: 'Traits' },
      { week: 8, topicId: 'generics', titleId: 'Generics', titleEn: 'Generics' },
      { week: 9, topicId: 'lifetimes', titleId: 'Lifetimes', titleEn: 'Lifetimes' },
      { week: 10, topicId: 'testing', titleId: 'Testing', titleEn: 'Testing' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Production Rust: smart pointer, concurrency, macro, unsafe, capstone project.',
    descEn: 'Production Rust: smart pointers, concurrency, macros, unsafe, capstone project.',
    weeks: [
      { week: 11, topicId: 'smart-pointers', titleId: 'Smart Pointers', titleEn: 'Smart Pointers' },
      { week: 12, topicId: 'concurrency', titleId: 'Concurrency', titleEn: 'Concurrency' },
      { week: 13, topicId: 'macros', titleId: 'Macros', titleEn: 'Macros' },
      { week: 14, topicId: 'capstone', titleId: 'Capstone: CLI + Library', titleEn: 'Capstone: CLI + Library' }
    ],
  }
];
