import type { LevelInfo } from '../curriculum';

// Spring Boot curriculum — research-backed structure
// Generated by generate-spring-materials.mjs
export const springCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Fundamental Spring Boot: setup, DI, controller, JPA, REST API — urutan resmi Spring Docs.',
    descEn: 'Spring Boot fundamentals: setup, DI, controllers, JPA, REST API — official Spring Docs order.',
    weeks: [
      { week: 1, topicId: 'setup-dan-proyek', titleId: 'Setup & Proyek Pertama', titleEn: 'Setup & First Project' },
      { week: 2, topicId: 'dependency-injection', titleId: 'Dependency Injection', titleEn: 'Dependency Injection' },
      { week: 3, topicId: 'rest-controller', titleId: 'REST Controller', titleEn: 'REST Controllers' },
      { week: 4, topicId: 'spring-data-jpa', titleId: 'Spring Data JPA', titleEn: 'Spring Data JPA' },
      { week: 5, topicId: 'rest-api-best-practices', titleId: 'REST API Best Practices', titleEn: 'REST API Best Practices' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Spring Boot production: security, testing, validation, actuator, messaging — Baeldung pathway.',
    descEn: 'Production Spring Boot: security, testing, validation, actuator, messaging — Baeldung pathway.',
    weeks: [
      { week: 6, topicId: 'spring-security', titleId: 'Spring Security', titleEn: 'Spring Security' },
      { week: 7, topicId: 'testing', titleId: 'Testing', titleEn: 'Testing' },
      { week: 8, topicId: 'validation', titleId: 'Validation', titleEn: 'Validation' },
      { week: 9, topicId: 'actuator-monitoring', titleId: 'Actuator & Monitoring', titleEn: 'Actuator & Monitoring' },
      { week: 10, topicId: 'messaging', titleId: 'Messaging', titleEn: 'Messaging' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Spring Boot expert: caching, async, deployment, microservices, capstone project.',
    descEn: 'Spring Boot expert: caching, async, deployment, microservices, capstone project.',
    weeks: [
      { week: 11, topicId: 'caching', titleId: 'Caching', titleEn: 'Caching' },
      { week: 12, topicId: 'async-scheduling', titleId: 'Async & Scheduling', titleEn: 'Async & Scheduling' },
      { week: 13, topicId: 'deployment', titleId: 'Deployment', titleEn: 'Deployment' },
      { week: 14, topicId: 'capstone', titleId: 'Capstone: E-Commerce API', titleEn: 'Capstone: E-Commerce API' }
    ],
  }
];
