import type { LevelInfo } from '../curriculum';

// Svelte curriculum — research-backed structure
// Generated by generate-svelte-materials.mjs
export const svelteCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar Svelte: template, reactivity, props, events, stores.',
    descEn: 'Svelte basics: template, reactivity, props, events, stores.',
    weeks: [
      { week: 1, topicId: 'dasar-svelte', titleId: 'Dasar Svelte & Template', titleEn: 'Svelte Basics & Template' },
      { week: 2, topicId: 'reactivity-statements', titleId: 'Reactivity & Statements', titleEn: 'Reactivity & Statements' },
      { week: 3, topicId: 'props-components', titleId: 'Props & Components', titleEn: 'Props & Components' },
      { week: 4, topicId: 'events-bindings', titleId: 'Events & Bindings', titleEn: 'Events & Bindings' },
      { week: 5, topicId: 'stores', titleId: 'Svelte Stores', titleEn: 'Svelte Stores' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Svelte menengah: routing, actions, transitions, proyek.',
    descEn: 'Intermediate Svelte: routing, actions, transitions, project.',
    weeks: [
      { week: 6, topicId: 'sveltekit-routing', titleId: 'SvelteKit Routing', titleEn: 'SvelteKit Routing' },
      { week: 7, topicId: 'actions-forms', titleId: 'Actions & Forms', titleEn: 'Actions & Forms' },
      { week: 8, topicId: 'lifecycle-context', titleId: 'Lifecycle & Context', titleEn: 'Lifecycle & Context' },
      { week: 9, topicId: 'transitions-animations', titleId: 'Transitions & Animations', titleEn: 'Transitions & Animations' },
      { week: 10, topicId: 'capstone', titleId: 'Capstone: SvelteKit App', titleEn: 'Capstone: SvelteKit App' }
    ],
  }
];
