import type { LevelInfo } from '../curriculum';

// Tailwind CSS curriculum — research-backed structure
// Generated by generate-tailwind-materials.mjs
export const tailwindCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Dasar Utility-First & Tipografi',
    nameEn: 'Utility-First Basics & Typography',
    descId: 'Filosofi utility-first, sistem skala spasi, tipografi, warna, dan border.',
    descEn: 'Utility-first philosophy, spacing scales, typography, colors, and borders.',
    weeks: [
      { week: 1, topicId: 'filosofi-utility-first-dan-tipografi', titleId: 'Filosofi Utility-First, Setup & Tipografi', titleEn: 'Utility-First Philosophy, Setup & Typography' },
      { week: 2, topicId: 'sistem-spasi-dan-box-model', titleId: 'Sistem Spasi, Ukuran, dan Box Model', titleEn: 'Spacing Scales, Sizing, and Box Model' },
      { week: 3, topicId: 'warna-background-border-dan-shadow', titleId: 'Warna, Latar Belakang, Border, dan Shadow', titleEn: 'Colors, Backgrounds, Borders, and Shadows' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Tata Letak & Responsivitas',
    nameEn: 'Layout & Responsiveness',
    descId: 'Flexbox, CSS Grid, breakpoint responsif mobile-first, dan dark mode.',
    descEn: 'Flexbox, CSS Grid, mobile-first responsive breakpoints, and dark mode.',
    weeks: [
      { week: 4, topicId: 'flexbox-layout-utilities', titleId: 'Tata Letak Flexbox dengan Tailwind', titleEn: 'Flexbox Layout with Tailwind' },
      { week: 5, topicId: 'css-grid-layout-utilities', titleId: 'Tata Letak CSS Grid dengan Tailwind', titleEn: 'CSS Grid Layout with Tailwind' },
      { week: 6, topicId: 'desain-responsif-dan-dark-mode', titleId: 'Desain Responsif & Arsitektur Dark Mode', titleEn: 'Responsive Design & Dark Mode Architecture' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Komponen & Proyek Antarmuka',
    nameEn: 'Components & Interface Project',
    descId: 'State modifiers, transisi animasi, pola komponen UI, dan proyek dashboard.',
    descEn: 'State modifiers, animated transitions, UI component patterns, and dashboard project.',
    weeks: [
      { week: 7, topicId: 'pseudo-class-state-dan-transisi', titleId: 'State Modifiers, Pseudo-Classes & Transisi', titleEn: 'State Modifiers, Pseudo-Classes & Transitions' },
      { week: 8, topicId: 'komposisi-komponen-ui', titleId: 'Komposisi Komponen UI: Card, Button, Form, Modal', titleEn: 'UI Component Composition: Cards, Buttons, Forms, Modals' },
      { week: 9, topicId: 'proyek-akhir-dashboard-admin', titleId: 'Proyek Akhir: Dashboard Admin Responsif Lengkap', titleEn: 'Final Project: Complete Responsive Admin Dashboard' }
    ],
  }
];
