import type { LevelInfo } from '../curriculum';

// TypeScript curriculum — research-backed structure
// Generated by generate-typescript-materials.mjs
export const typescriptCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Dasar Tipe & Interface',
    nameEn: 'Types & Interfaces Foundation',
    descId: 'Sintaks dasar, tipe primitif, inference, fungsi, dan interface.',
    descEn: 'Basic syntax, primitive types, inference, functions, and interfaces.',
    weeks: [
      { week: 1, topicId: 'pengantar-typescript', titleId: 'Pengantar TypeScript', titleEn: 'Introduction to TypeScript' },
      { week: 2, topicId: 'advanced-types', titleId: 'Advanced Types', titleEn: 'Advanced Types' },
      { week: 3, topicId: 'fungsi-typescript', titleId: 'Functions & Signatures', titleEn: 'Functions & Signatures' },
      { week: 4, topicId: 'interfaces-type-aliases', titleId: 'Interfaces & Type Aliases', titleEn: 'Interfaces & Type Aliases' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Generics & Konsep Lanjutan',
    nameEn: 'Generics & Advanced Concepts',
    descId: 'Generics, OOP classes, utility types, dan konfigurasi compiler.',
    descEn: 'Generics, OOP classes, utility types, and compiler configuration.',
    weeks: [
      { week: 5, topicId: 'generics', titleId: 'Generics', titleEn: 'Generics' },
      { week: 6, topicId: 'classes-oop', titleId: 'Classes & OOP', titleEn: 'Classes & OOP' },
      { week: 7, topicId: 'utility-types', titleId: 'Utility Types', titleEn: 'Utility Types' },
      { week: 8, topicId: 'typescript-config', titleId: 'TypeScript Config', titleEn: 'TypeScript Configuration' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Arsitektur Type-Safe & Proyek Akhir',
    nameEn: 'Type-Safe Architecture & Final Project',
    descId: 'Testing, design patterns, integrasi API, dan proyek aplikasi type-safe.',
    descEn: 'Testing, design patterns, API integrations, and type-safe application project.',
    weeks: [
      { week: 9, topicId: 'testing-typescript', titleId: 'Testing TypeScript', titleEn: 'Testing TypeScript' },
      { week: 10, topicId: 'patterns-typescript', titleId: 'Design Patterns TS', titleEn: 'TypeScript Design Patterns' },
      { week: 11, topicId: 'api-advanced-types', titleId: 'Advanced Type Manipulation', titleEn: 'Advanced Type Manipulation' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: Type-Safe API Client', titleEn: 'Capstone: Type-Safe API Client' }
    ],
  }
];
