import type { LevelInfo } from '../curriculum';

// TypeScript curriculum — research-backed structure
// Generated by generate-typescript-materials.mjs
export const typescriptCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'TypeScript Lengkap',
    nameEn: 'Complete TypeScript',
    descId: 'Dari nol hingga mahir: tipe data, interface, generics, dan pattern TypeScript production.',
    descEn: 'From zero to expert: types, interfaces, generics, and production TypeScript patterns.',
    weeks: [
      { week: 1, topicId: 'pengantar-typescript', titleId: 'Pengantar TypeScript', titleEn: 'Introduction to TypeScript' },
      { week: 2, topicId: 'advanced-types', titleId: 'Advanced Types', titleEn: 'Advanced Types' },
      { week: 3, topicId: 'fungsi-typescript', titleId: 'Functions & Signatures', titleEn: 'Functions & Signatures' },
      { week: 4, topicId: 'interfaces-type-aliases', titleId: 'Interfaces & Type Aliases', titleEn: 'Interfaces & Type Aliases' },
      { week: 5, topicId: 'generics', titleId: 'Generics', titleEn: 'Generics' },
      { week: 6, topicId: 'classes-oop', titleId: 'Classes & OOP', titleEn: 'Classes & OOP' },
      { week: 7, topicId: 'utility-types', titleId: 'Utility Types', titleEn: 'Utility Types' },
      { week: 8, topicId: 'typescript-config', titleId: 'TypeScript Config', titleEn: 'TypeScript Configuration' },
      { week: 9, topicId: 'testing-typescript', titleId: 'Testing TypeScript', titleEn: 'Testing TypeScript' },
      { week: 10, topicId: 'patterns-typescript', titleId: 'Design Patterns TS', titleEn: 'TypeScript Design Patterns' },
      { week: 11, topicId: 'api-advanced-types', titleId: 'Advanced Type Manipulation', titleEn: 'Advanced Type Manipulation' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: Type-Safe API Client', titleEn: 'Capstone: Type-Safe API Client' }
    ],
  }
];
