import type { LevelInfo } from '../curriculum';

// Vue curriculum — research-backed structure
// Generated by generate-vue-materials.mjs
export const vueCurriculum: LevelInfo[] = [
  {
    levelId: 'beginer',
    nameId: 'Pemula',
    nameEn: 'Beginner',
    descId: 'Dasar Vue: template, reactivity, directives, events.',
    descEn: 'Vue basics: template, reactivity, directives, events.',
    weeks: [
      { week: 1, topicId: 'dasar-vue', titleId: 'Dasar Vue & Template Syntax', titleEn: 'Vue Basics & Template Syntax' },
      { week: 2, topicId: 'reactivity-composition', titleId: 'Reactivity & Composition API', titleEn: 'Reactivity & Composition API' },
      { week: 3, topicId: 'directives-events', titleId: 'Directives & Events', titleEn: 'Directives & Events' },
      { week: 4, topicId: 'components-props', titleId: 'Components & Props', titleEn: 'Components & Props' }
    ],
  },
  {
    levelId: 'intermediate',
    nameId: 'Menengah',
    nameEn: 'Intermediate',
    descId: 'Vue menengah: components, router, Pinia.',
    descEn: 'Intermediate Vue: components, router, Pinia.',
    weeks: [
      { week: 5, topicId: 'vue-router', titleId: 'Vue Router', titleEn: 'Vue Router' },
      { week: 6, topicId: 'pinia', titleId: 'Pinia State Management', titleEn: 'Pinia State Management' },
      { week: 7, topicId: 'lifecycle-watchers', titleId: 'Lifecycle & Watchers', titleEn: 'Lifecycle & Watchers' },
      { week: 8, topicId: 'provide-inject', titleId: 'Provide/Inject & Teleport', titleEn: 'Provide/Inject & Teleport' }
    ],
  },
  {
    levelId: 'advanced',
    nameId: 'Lanjutan',
    nameEn: 'Advanced',
    descId: 'Vue lanjutan: testing, performance, Nuxt, proyek.',
    descEn: 'Advanced Vue: testing, performance, Nuxt, project.',
    weeks: [
      { week: 9, topicId: 'testing-vue', titleId: 'Testing Vue Components', titleEn: 'Testing Vue Components' },
      { week: 10, topicId: 'performance-nuxt', titleId: 'Performance & Nuxt', titleEn: 'Performance & Nuxt' },
      { week: 11, topicId: 'animations-transitions', titleId: 'Animations & Transitions', titleEn: 'Animations & Transitions' },
      { week: 12, topicId: 'capstone', titleId: 'Capstone: SaaS Dashboard', titleEn: 'Capstone: SaaS Dashboard' }
    ],
  }
];
